import { CustomFlowNode, CustomFlowEdge, CampaignKnowledge } from '../types/flow';

export interface CampaignTemplate {
  id: string;
  name: string;
  tagline: string;
  category: string;
  knowledge: CampaignKnowledge;
  initialNodes: CustomFlowNode[];
  initialEdges: CustomFlowEdge[];
}

export const CAMPAIGN_TEMPLATES: CampaignTemplate[] = [
  {
    id: 'vianet-renewal-retention',
    name: 'Vianet Internet Renewal & Retention',
    tagline: 'Outbound renewal agent with Wi-Fi 6 plans, Samba packs, ViaTV add-on & usage discovery',
    category: 'Telecom & ISP',
    knowledge: {
      campaignId: 'vianet-renewal-retention',
      campaignName: 'Vianet Internet Renewal Campaign',
      description: 'Outbound renewal campaign for Vianet Communications verifying contact identity, assessing internet usage (light vs heavy vs general), and guiding customers through Wi-Fi 6 or Samba renewal packages with optional ViaTV.',
      agentPersona: {
        name: 'Aagaman',
        role: 'Customer Care & Renewal Executive',
        company: 'Vianet',
        tone: 'friendly_professional',
        speakingRate: 1.0,
        voice: 'Pratikshya',
      },
      leadProfile: {
        name: 'Bijay Shrestha',
        company: 'Home Subscriber',
        phone: '+977 9841234567',
        email: 'bijay.shrestha@example.com',
        attributes: {
          current_plan: '100 Mbps Samba Plus Plan',
          monthlySpend: 'Rs. 1,300/mo',
          tenure: '1.5 Years',
          contractStatus: 'Expiring in 5 days',
          customerId: 'VIA-98241',
        },
      },
      complianceNotice: 'This call is recorded by Vianet Communication Ltd for service quality assurance.',
      knowledgeItems: [
        {
          id: 'vianet-wifi6-plans',
          title: 'Vianet Wi-Fi 6 Packages',
          contentType: 'product_offer',
          tags: ['wifi6', 'plans', 'pro', 'ultra', 'speeds'],
          content: 'Pro WiFi 6 (250 Mbps): 3 Months Rs. 4,000 | 12 Months Rs. 13,800. Ultra WiFi 6 (400 Mbps): 3 Months Rs. 4,300 | 12 Months Rs. 15,600. Ultra Max WiFi 6 (600 Mbps): 3 Months Rs. 6,000 | 12 Months Rs. 22,500. All Wi-Fi 6 plans include dual-band smart router setup.',
          source: 'Vianet Residential Wi-Fi 6 Sheet',
          version: '2026.1',
          status: 'approved',
        },
        {
          id: 'vianet-samba-plans',
          title: 'Vianet Samba Packs',
          contentType: 'product_offer',
          tags: ['samba', 'budget', 'mini', 'plus', 'pro', 'ultra'],
          content: 'Mini 50 Mbps: 1M Rs. 950 | 3M Rs. 2,600 | 12M Rs. 7,900. Plus 100 Mbps: 1M Rs. 1,300 | 3M Rs. 3,450 | 12M Rs. 8,500. Pro 200 Mbps: 1M Rs. 1,500 | 3M Rs. 4,000 | 12M Rs. 11,200. Ultra 300 Mbps: 1M Rs. 1,850 | 3M Rs. 5,000 | 12M Rs. 13,800 (includes 1 Month Free).',
          source: 'Vianet Samba Rate Card',
          version: '2026.1',
          status: 'approved',
        },
        {
          id: 'vianet-viatv',
          title: 'ViaTV IPTV Subscription & Features',
          contentType: 'product_offer',
          tags: ['viatv', 'iptv', 'tv', 'channels'],
          content: 'ViaTV includes 200+ live HD/SD channels, 7-day Catch-up TV, Pause & Play, and mobile app access. Subscription: 1 Month Rs. 250 | 3 Months Rs. 750 | 12 Months Rs. 3,000. Primary STB activation fee is Rs. 500 for 12 months with Rs. 500 refundable deposit.',
          source: 'ViaTV Product Guide',
          version: '2026.1',
          status: 'approved',
        },
        {
          id: 'vianet-support-contacts',
          title: 'Vianet Customer Care & Contacts',
          contentType: 'company_information',
          tags: ['support', 'phone', 'help', 'contact'],
          content: 'Inside Kathmandu Valley & Banepa: 01-5970444. General Support Mobile: 9801046410. Toll-Free for NTC callers: 16600188444. New Sales: 01-5970644. All prices are subject to 13% VAT and standard Fair Usage Policy (FUP).',
          source: 'Vianet Support Directory',
          version: '2026.1',
          status: 'approved',
        },
      ],
      globalObjections: [
        {
          id: 'obj-ai-identity',
          trigger: 'Are you an AI or automated system?',
          response: 'Namaste! I am Aagaman, an automated AI assistant calling on behalf of Vianet Customer Care. I am reaching out to ensure you receive our special loyalty renewal discount and Wi-Fi 6 upgrade before your subscription expires.',
          resumeFlow: true,
        },
        {
          id: 'obj-busy',
          trigger: 'I am busy right now',
          response: 'I completely understand Mr. {{lead_name}}! I can text you our renewal package summary and direct payment link to your phone right now so you can review it whenever you are free. Would that be helpful?',
          resumeFlow: false,
        },
        {
          id: 'obj-price',
          trigger: 'It is too expensive or price concern',
          response: 'We actually have 12-month Samba packs starting at just Rs. 7,900 for the full year, which brings your monthly internet cost down significantly, plus free ViaTV bundles. Shall we look at a budget-friendly option?',
          resumeFlow: true,
        },
      ],
      faqs: [
        {
          id: 'faq-wifi6',
          question: 'What is special about Vianet Wi-Fi 6?',
          answer: 'Vianet Wi-Fi 6 provides dual-band gigabit routers with 4x higher capacity, lower latency for gaming and video calls, and wider coverage across all your rooms without dead zones.',
          keywords: ['wifi 6', 'wi-fi 6', 'router', 'coverage', 'speed'],
        },
        {
          id: 'faq-pricing-annual',
          question: 'What is the cheapest 1-year renewal plan?',
          answer: 'Our Mini 50 Mbps plan is Rs. 7,900 for 12 months, and our popular Plus 100 Mbps plan is Rs. 8,500 for a full year. Both provide unlimited reliable fiber internet.',
          keywords: ['cheap', 'cost', 'price', 'rates', 'annual', '12 months', 'year'],
        },
        {
          id: 'faq-payment-methods',
          question: 'How can I pay for my renewal?',
          answer: 'You can pay instantly online through eSewa, Khalti, connectIPS, Vianet Mobile App, or online banking. We can text you a direct 1-click renewal link.',
          keywords: ['pay', 'payment', 'esewa', 'khalti', 'online', 'bank'],
        },
      ],
    },
    initialNodes: [
      {
        id: 'node-greeting',
        type: 'greeting',
        position: { x: 400, y: 40 },
        data: {
          type: 'greeting',
          label: 'Step 1: Greeting & Verification',
          description: 'Identity confirmation with lead',
          openingScript: 'Hello. This is Aagaman from Vianet. Am I talking with Mr. {{lead_name}}?',
          voiceStyle: 'Friendly & Professional',
        },
      },
      {
        id: 'node-hangup-wrong-number',
        type: 'hangup',
        position: { x: 50, y: 160 },
        data: {
          type: 'hangup',
          label: 'Exit: Wrong Number',
          description: 'Polite exit if caller is not the intended customer',
          closingScript: 'I apologize for disturbing you. Have a great day!',
          disposition: 'wrong_number',
          sendSummarySms: false,
        },
      },
      {
        id: 'node-q2-quick-chat',
        type: 'question',
        position: { x: 400, y: 180 },
        data: {
          type: 'question',
          label: 'Step 2: Quick Chat Permission',
          description: 'Check customer availability',
          speechPrompt: 'Glad to connect with you, Mr. {{lead_name}}! Do you have a couple of minutes for a quick chat regarding your Vianet internet service?',
          allowBargeIn: true,
          maxWaitSeconds: 5,
          maxRepeats: 2,
        },
      },
      {
        id: 'node-hangup-busy',
        type: 'hangup',
        position: { x: 750, y: 280 },
        data: {
          type: 'hangup',
          label: 'Exit: Callback Scheduled',
          description: 'Graceful exit when subscriber is busy',
          closingScript: 'No problem at all. We will reach back out to you at a more convenient time. Have a wonderful day!',
          disposition: 'callback_scheduled',
          sendSummarySms: true,
        },
      },
      {
        id: 'node-q3-expiring-plan',
        type: 'question',
        position: { x: 400, y: 320 },
        data: {
          type: 'question',
          label: 'Step 3: Plan Expiry & Renewal Interest',
          description: 'Notice of expiry and offer to renew',
          speechPrompt: 'Your current {{current_plan}} is expiring in a few days. We have special loyalty renewal offers and speed upgrades available today. Are you interested in renewing?',
          allowBargeIn: true,
          maxWaitSeconds: 5,
          maxRepeats: 2,
        },
      },
      {
        id: 'node-rebuttal-retention',
        type: 'knowledge',
        position: { x: 100, y: 440 },
        data: {
          type: 'knowledge',
          label: 'Rebuttal: Loyalty Benefits & Retention',
          description: 'Address cancellation or hesitation',
          objectionTopic: 'Considering switching or not renewing',
          rebuttalScript: 'Before you decide, we have introduced high-performance Wi-Fi 6 dual-band routers, and our 12-month Samba packs include up to 1 month free plus over 200 ViaTV channels. May I ask what your biggest concern was with the current service?',
          returnToPrevious: true,
        },
      },
      {
        id: 'node-hangup-not-interested',
        type: 'hangup',
        position: { x: -120, y: 560 },
        data: {
          type: 'hangup',
          label: 'Exit: Not Interested',
          description: 'Subscriber firmly declines renewal',
          closingScript: 'Thank you for your time with Vianet. If you ever change your mind or need assistance, call us anytime at 01-5970444. Have a good day!',
          disposition: 'disqualified_not_interested',
          sendSummarySms: false,
        },
      },
      {
        id: 'node-q4-usage-discovery',
        type: 'question',
        position: { x: 400, y: 470 },
        data: {
          type: 'question',
          label: 'Step 4: Internet Usage Discovery',
          description: 'Understand household bandwidth needs',
          speechPrompt: 'To help find the best renewal plan for you, what do you mostly use your internet for at home?',
          allowBargeIn: true,
          maxWaitSeconds: 6,
          maxRepeats: 2,
        },
      },
      {
        id: 'node-router-usage',
        type: 'scenarioBranch',
        position: { x: 400, y: 620 },
        data: {
          type: 'scenarioBranch',
          label: 'Step 4B: Usage Router',
          description: 'Classifies caller usage into heavy, light, or general',
          evaluationCriteria: 'Determine whether household internet usage is heavy (gaming/4K), light (browsing/social), or general/unsure',
          branches: [
            {
              id: 'branch-heavy',
              label: 'Heavy Usage (Gaming, 4K, Work)',
              description: 'Customer streams 4K, plays online games, or has many devices',
              intentKey: 'heavy_usage',
              color: '#10b981',
              targetHandle: 'h-heavy',
            },
            {
              id: 'branch-light',
              label: 'Light Usage (Social, Browsing)',
              description: 'Customer only uses social media, news, and light browsing',
              intentKey: 'light_usage',
              color: '#3b82f6',
              targetHandle: 'h-light',
            },
            {
              id: 'branch-unsure',
              label: 'Unsure / Mixed Household',
              description: 'Customer is unsure or has general household usage',
              intentKey: 'unsure_usage',
              color: '#f59e0b',
              targetHandle: 'h-unsure',
            },
          ],
        },
      },
      {
        id: 'node-q5-heavy-services',
        type: 'question',
        position: { x: 150, y: 770 },
        data: {
          type: 'question',
          label: 'Step 5A: Wi-Fi 6 Offer (Heavy)',
          description: 'For 4K streaming, gaming, and multiple users',
          speechPrompt: 'For heavy streaming and online gaming, our Wi-Fi 6 Ultra-Fi 400 Mbps at Rs. 15,600 per year or 250 Mbps at Rs. 12,900 is ideal. Which speed would work best for your home?',
          allowBargeIn: true,
          maxWaitSeconds: 5,
        },
      },
      {
        id: 'node-q5-light-services',
        type: 'question',
        position: { x: 650, y: 770 },
        data: {
          type: 'question',
          label: 'Step 5B: Samba Pack Offer (Light)',
          description: 'Budget-friendly 50 Mbps or 100 Mbps',
          speechPrompt: 'For light everyday browsing and social media, our Samba Plus 100 Mbps is great value at Rs. 8,500 per year, or Mini 50 Mbps at Rs. 7,900. Which one of those speeds would you prefer?',
          allowBargeIn: true,
          maxWaitSeconds: 5,
        },
      },
      {
        id: 'node-q5-general-services',
        type: 'question',
        position: { x: 400, y: 770 },
        data: {
          type: 'question',
          label: 'Step 5C: 200/250 Mbps Offer (General)',
          description: 'Balanced sweet-spot plan for family homes',
          speechPrompt: 'Understood! For an average household with 4 to 6 connected devices, our Samba Pro 200 Mbps at Rs. 11,200 per year or Pro WiFi 6 250 Mbps at Rs. 12,900 is our most popular package. Would you prefer 200 Mbps or 250 Mbps?',
          allowBargeIn: true,
          maxWaitSeconds: 5,
        },
      },
      {
        id: 'node-q6-tv-services',
        type: 'question',
        position: { x: 400, y: 920 },
        data: {
          type: 'question',
          label: 'Step 6: ViaTV Add-on Option',
          description: 'Optionally add ViaTV channels to bundle',
          speechPrompt: 'Great choice! We also offer ViaTV with over 200 live channels and 7-day catch-up for just Rs. 3,000 for the full year. Would you like to bundle ViaTV, or would you prefer internet only?',
          allowBargeIn: true,
          maxWaitSeconds: 5,
        },
      },
      {
        id: 'node-q6-tv-details',
        type: 'question',
        position: { x: 720, y: 1060 },
        data: {
          type: 'question',
          label: 'ViaTV Features & Channels',
          description: 'Explains 200+ live channels, 7-day catch-up, and Rs. 3,000/yr price',
          speechPrompt: 'ViaTV includes over 200 live HD and SD channels, 7-day Catch-up TV so you can pause and rewind your shows, plus YouTube on TV. For the full year it is just Rs. 3,000, which is only Rs. 250 a month, with a Set-Top Box included. Would you like to add it to your plan, or stick with internet only?',
          allowBargeIn: true,
          maxWaitSeconds: 5,
        },
      },
      {
        id: 'node-tv-bundle-added',
        type: 'question',
        position: { x: 180, y: 1060 },
        data: {
          type: 'question',
          label: 'ViaTV Bundle Confirmed',
          description: 'Bundle confirmed with 200+ channels',
          speechPrompt: 'Excellent! I have added the ViaTV bundle with over 200 channels and Set-Top Box to your renewal order. Ready for me to send the renewal payment link to your mobile number?',
          allowBargeIn: true,
          maxWaitSeconds: 5,
        },
      },
      {
        id: 'node-tv-internet-only',
        type: 'question',
        position: { x: 450, y: 1060 },
        data: {
          type: 'question',
          label: 'Internet-Only Confirmed',
          description: 'Proceed with high-speed internet only',
          speechPrompt: 'Understood, we will keep it as high-speed internet only with no extra TV charges. Shall I go ahead and send your renewal payment link to your mobile number?',
          allowBargeIn: true,
          maxWaitSeconds: 5,
        },
      },
      {
        id: 'node-action-dispatch-link',
        type: 'action',
        position: { x: 350, y: 1220 },
        data: {
          type: 'action',
          label: 'Send Renewal SMS & Payment Link',
          description: 'Trigger SMS with eSewa / Khalti link',
          actionType: 'send_sms',
          actionConfig: {
            title: 'Vianet Renewal Link Sent to {{phone}}',
            crmTag: 'vianet_renewal_link_sent',
          },
        },
      },
      {
        id: 'node-hangup-success',
        type: 'hangup',
        position: { x: 350, y: 1370 },
        data: {
          type: 'hangup',
          label: 'Step 7: Renewal Confirmed & Wrap-up',
          description: 'Thank customer and end call',
          closingScript: 'Wonderful! I have sent the renewal confirmation and direct payment link to your mobile number. Thank you for choosing Vianet, Mr. {{lead_name}}, and have a great day!',
          disposition: 'meeting_booked',
          sendSummarySms: true,
        },
      },
    ],
    initialEdges: [
      {
        id: 'edge-greet-yes',
        source: 'node-greeting',
        target: 'node-q2-quick-chat',
        type: 'condition',
        data: { label: 'Yes / This is him / Speaking', intent: 'positive' },
      },
      {
        id: 'edge-greet-wrong',
        source: 'node-greeting',
        target: 'node-hangup-wrong-number',
        type: 'condition',
        data: { label: 'Wrong Number / Not him', intent: 'negative' },
      },
      {
        id: 'edge-greet-busy',
        source: 'node-greeting',
        target: 'node-hangup-busy',
        type: 'condition',
        data: { label: 'Busy / Call later', intent: 'busy' },
      },
      {
        id: 'edge-chat-yes',
        source: 'node-q2-quick-chat',
        target: 'node-q3-expiring-plan',
        type: 'condition',
        data: { label: 'Yes / Free for quick chat', intent: 'positive' },
      },
      {
        id: 'edge-chat-busy',
        source: 'node-q2-quick-chat',
        target: 'node-hangup-busy',
        type: 'condition',
        data: { label: 'No / Busy right now', intent: 'busy' },
      },
      {
        id: 'edge-renew-yes',
        source: 'node-q3-expiring-plan',
        target: 'node-q4-usage-discovery',
        type: 'condition',
        data: { label: 'Yes / Interested in renewal', intent: 'positive' },
      },
      {
        id: 'edge-renew-hesitant',
        source: 'node-q3-expiring-plan',
        target: 'node-rebuttal-retention',
        type: 'condition',
        data: { label: 'Not sure / Considering switching', intent: 'objection', isObjection: true },
      },
      {
        id: 'edge-rebuttal-continue',
        source: 'node-rebuttal-retention',
        target: 'node-q4-usage-discovery',
        type: 'condition',
        data: { label: 'Willing to hear offers', intent: 'positive' },
      },
      {
        id: 'edge-rebuttal-quit',
        source: 'node-rebuttal-retention',
        target: 'node-hangup-not-interested',
        type: 'condition',
        data: { label: 'Definitely not interested', intent: 'negative' },
      },
      {
        id: 'edge-usage-to-router',
        source: 'node-q4-usage-discovery',
        target: 'node-router-usage',
        type: 'condition',
        data: { label: 'Usage explained', intent: 'positive' },
      },
      {
        id: 'edge-router-heavy',
        source: 'node-router-usage',
        target: 'node-q5-heavy-services',
        type: 'condition',
        data: { label: 'Heavy (Gaming, 4K, Multiple Users)', intent: 'heavy_usage' },
      },
      {
        id: 'edge-router-light',
        source: 'node-router-usage',
        target: 'node-q5-light-services',
        type: 'condition',
        data: { label: 'Light (Social Media, News)', intent: 'light_usage' },
      },
      {
        id: 'edge-router-unsure',
        source: 'node-router-usage',
        target: 'node-q5-general-services',
        type: 'condition',
        data: { label: 'Unsure / Mixed Household', intent: 'general_usage' },
      },
      {
        id: 'edge-heavy-to-tv',
        source: 'node-q5-heavy-services',
        target: 'node-q6-tv-services',
        type: 'condition',
        data: { label: 'Selects 250 or 400 Mbps', intent: 'positive' },
      },
      {
        id: 'edge-light-to-tv',
        source: 'node-q5-light-services',
        target: 'node-q6-tv-services',
        type: 'condition',
        data: { label: 'Selects 50 or 100 Mbps', intent: 'positive' },
      },
      {
        id: 'edge-general-to-tv',
        source: 'node-q5-general-services',
        target: 'node-q6-tv-services',
        type: 'condition',
        data: { label: 'Selects 200 or 250 Mbps', intent: 'positive' },
      },
      {
        id: 'edge-tv-interested',
        source: 'node-q6-tv-services',
        target: 'node-tv-bundle-added',
        type: 'condition',
        data: { label: 'Interested / Add ViaTV', intent: 'positive' },
      },
      {
        id: 'edge-tv-not-interested',
        source: 'node-q6-tv-services',
        target: 'node-tv-internet-only',
        type: 'condition',
        data: { label: 'Not Interested / Internet Only', intent: 'negative' },
      },
      {
        id: 'edge-tv-tell-me-more',
        source: 'node-q6-tv-services',
        target: 'node-q6-tv-details',
        type: 'condition',
        data: { label: 'Tell Me More / What Channels?', intent: 'inquiry' },
      },
      {
        id: 'edge-tv-details-yes',
        source: 'node-q6-tv-details',
        target: 'node-tv-bundle-added',
        type: 'condition',
        data: { label: 'Add ViaTV / Sounds Good', intent: 'positive' },
      },
      {
        id: 'edge-tv-details-no',
        source: 'node-q6-tv-details',
        target: 'node-tv-internet-only',
        type: 'condition',
        data: { label: 'Internet Only / Skip TV', intent: 'negative' },
      },
      {
        id: 'edge-tv-bundle-to-action',
        source: 'node-tv-bundle-added',
        target: 'node-action-dispatch-link',
        type: 'condition',
        data: { label: 'Yes / Send Link', intent: 'positive' },
      },
      {
        id: 'edge-tv-net-only-to-action',
        source: 'node-tv-internet-only',
        target: 'node-action-dispatch-link',
        type: 'condition',
        data: { label: 'Yes / Send Link', intent: 'positive' },
      },
      {
        id: 'edge-action-to-success',
        source: 'node-action-dispatch-link',
        target: 'node-hangup-success',
        type: 'condition',
        data: { label: 'Link dispatched', intent: 'next' },
      },
    ],
  },
  {
    id: 'b2b-saas-qualification',
    name: 'B2B SaaS Demo Qualification',
    tagline: 'High-converting outbound SDR agent with objection rebuttals & calendar booking',
    category: 'Sales & SDR',
    knowledge: {
      campaignId: 'b2b-saas-qualification',
      campaignName: 'DataPilot Cloud Optimizer SDR Outreach',
      description: 'Outbound campaign targeting VP/Director of Engineering to qualify and schedule 15-min live architecture demos.',
      agentPersona: {
        name: 'Sarah Chen',
        role: 'Senior Solutions Specialist',
        company: 'DataPilot AI',
        tone: 'consultative',
        speakingRate: 1.0,
        voice: 'en-US-Standard-C',
      },
      leadProfile: {
        name: 'Alex Mercer',
        company: 'Apex Logistics',
        phone: '+1 (555) 382-9912',
        email: 'alex.mercer@apexlogistics.io',
        attributes: {
          role: 'Head of Infrastructure',
          cloudProvider: 'AWS & Kubernetes',
          estimatedSpend: '$45,000/mo',
        },
      },
      complianceNotice: 'This call is recorded for quality assurance and training purposes.',
      knowledgeItems: [],
      globalObjections: [
        {
          id: 'obj-ai-check',
          trigger: 'Are you an AI or a real person?',
          response: "I'm Sarah, an AI voice assistant from DataPilot! I'm reaching out directly to see if exploring automated AWS cost reduction makes sense for your team before looping in our lead engineer.",
          resumeFlow: true,
        },
        {
          id: 'obj-how-got-number',
          trigger: 'How did you get my number?',
          response: 'Your contact was listed in our verified B2B infrastructure directory for Apex Logistics engineering leadership. I apologize if this caught you at an inconvenient time!',
          resumeFlow: true,
        },
      ],
      faqs: [
        {
          id: 'faq-pricing',
          question: 'How much does DataPilot cost?',
          answer: 'We operate on a pure performance model — zero upfront software fee, taking only 15% of the net savings verified on your monthly cloud invoice.',
          keywords: ['cost', 'price', 'pricing', 'expensive', 'fee'],
        },
        {
          id: 'faq-security',
          question: 'Is it SOC2 compliant and safe for production clusters?',
          answer: 'Yes, we are SOC 2 Type II certified and read-only by default. We never access user data or application payloads.',
          keywords: ['security', 'soc2', 'safe', 'compliance', 'safe'],
        },
      ],
    },
    initialNodes: [
      {
        id: 'node-greeting',
        type: 'greeting',
        position: { x: 400, y: 50 },
        data: {
          type: 'greeting',
          label: 'Outbound Greeting',
          description: 'Initial greeting with prospect',
          openingScript: 'Hi {{lead_name}}, this is Sarah from DataPilot. I noticed your team at {{company}} is managing Kubernetes workloads — do you have 30 seconds?',
          voiceStyle: 'Friendly & confident',
          gatekeeperHandling: 'I am calling to follow up with Alex regarding Apex Logistics cloud optimization project.',
        },
      },
      {
        id: 'node-value-pitch',
        type: 'question',
        position: { x: 650, y: 280 },
        data: {
          type: 'question',
          label: 'Value Hook & Discovery',
          description: 'Introduce automated savings and test initiative priority',
          speechPrompt: 'Awesome! We help DevOps teams automatically trim 30% off EC2 and container spend without modifying code. Is cloud efficiency or cluster scaling an active priority this quarter?',
          variableToExtract: 'cloud_priority',
          allowBargeIn: true,
          maxWaitSeconds: 6,
          maxRepeats: 2,
          silencePrompt: 'Just wanted to check if you can hear me OK?',
        },
      },
      {
        id: 'node-intent-branch',
        type: 'scenarioBranch',
        position: { x: 650, y: 540 },
        data: {
          type: 'scenarioBranch',
          label: 'Lead Intent Router',
          description: 'Branch dynamically based on prospect sentiment and objections',
          evaluationCriteria: 'Analyze caller response for interest, budget objection, timing constraint, or flat refusal',
          branches: [
            {
              id: 'branch-positive',
              label: 'Positive / Interested',
              description: 'Prospect confirms interest or expresses pain point',
              intentKey: 'positive_interest',
              color: '#10b981',
              targetHandle: 'handle-pos',
            },
            {
              id: 'branch-price',
              label: 'Budget / Price Objection',
              description: 'Mentions lack of budget or cost worries',
              intentKey: 'price_objection',
              color: '#f59e0b',
              targetHandle: 'handle-price',
            },
            {
              id: 'branch-busy',
              label: 'Busy / Driving / Callback',
              description: 'Requests callback or is in middle of meeting',
              intentKey: 'timing_busy',
              color: '#3b82f6',
              targetHandle: 'handle-busy',
            },
            {
              id: 'branch-dnc',
              label: 'Not Interested / DNC',
              description: 'Direct rejection or remove from list',
              intentKey: 'not_interested',
              color: '#ef4444',
              targetHandle: 'handle-dnc',
            },
          ],
        },
      },
      {
        id: 'node-rebuttal-price',
        type: 'knowledge',
        position: { x: 250, y: 780 },
        data: {
          type: 'knowledge',
          label: 'Budget Objection Rebuttal',
          description: 'Clarify performance-only model and loop back',
          category: 'Objection Handling',
          objectionTopic: 'No Budget Available',
          rebuttalScript: 'Totally understand budget freezes! That is actually why our model requires zero software budget — we only take a percentage of the actual cloud savings we prove on your AWS bill. Does a 15-minute review with our systems architect sound unreasonable?',
          returnToPrevious: true,
          followUpPrompt: 'Would Tuesday or Thursday morning work better for you?',
        },
      },
      {
        id: 'node-action-book',
        type: 'action',
        position: { x: 750, y: 800 },
        data: {
          type: 'action',
          label: 'Book Demo Slot',
          description: 'Trigger calendar webhook and lock appointment slot',
          actionType: 'calendar_booking',
          actionConfig: {
            title: '15-Min Cloud Optimization Audit with DataPilot',
            details: 'Invitee: {{lead_name}} ({{company}})',
            targetPhone: '{{phone}}',
            crmTag: 'lead_qualified_demo_booked',
          },
        },
      },
      {
        id: 'node-action-callback',
        type: 'action',
        position: { x: 1150, y: 780 },
        data: {
          type: 'action',
          label: 'Dispatch SMS Callback',
          description: 'Send self-scheduling calendar link via SMS',
          actionType: 'send_sms',
          actionConfig: {
            title: 'DataPilot Scheduling Link',
            details: 'Hi {{lead_name}}, as discussed, here is the link to grab 10 mins whenever convenient: cal.datapilot.ai/demo',
            crmTag: 'callback_requested_sms_sent',
          },
        },
      },
      {
        id: 'node-success-hangup',
        type: 'hangup',
        position: { x: 750, y: 1040 },
        data: {
          type: 'hangup',
          label: 'Demo Confirmed & Wrap Up',
          description: 'Thank the caller and send calendar invite',
          closingScript: "You're all set, {{lead_name}}! You will receive an invite from our principal engineer for Thursday at 10 AM. Thanks for your time and have a productive day!",
          disposition: 'meeting_booked',
          sendSummarySms: true,
        },
      },
      {
        id: 'node-callback-hangup',
        type: 'hangup',
        position: { x: 1150, y: 1040 },
        data: {
          type: 'hangup',
          label: 'Callback Scheduled Wrap Up',
          description: 'Polite close for busy lead',
          closingScript: 'Just texted the direct link to {{phone}}. Look forward to connecting later. Have a wonderful rest of your day!',
          disposition: 'callback_scheduled',
          sendSummarySms: true,
        },
      },
      {
        id: 'node-dnc-hangup',
        type: 'hangup',
        position: { x: 1450, y: 780 },
        data: {
          type: 'hangup',
          label: 'Polite DNC Disconnect',
          description: 'Honor opt-out request and tag CRM',
          closingScript: 'No problem at all. I have noted your preference and removed your number from our outreach. Thank you for your time.',
          disposition: 'dnc_requested',
          sendSummarySms: false,
        },
      },
    ],
    initialEdges: [
      {
        id: 'edge-greeting-human',
        source: 'node-greeting',
        sourceHandle: 'human',
        target: 'node-value-pitch',
        data: { label: 'Human Answered', intent: 'human_connected' },
      },
      {
        id: 'edge-pitch-branch',
        source: 'node-value-pitch',
        target: 'node-intent-branch',
        data: { label: 'Caller Responds' },
      },
      {
        id: 'edge-branch-pos',
        source: 'node-intent-branch',
        sourceHandle: 'handle-pos',
        target: 'node-action-book',
        data: { label: 'Interested / Needs Savings', intent: 'positive', color: '#10b981' },
      },
      {
        id: 'edge-branch-price',
        source: 'node-intent-branch',
        sourceHandle: 'handle-price',
        target: 'node-rebuttal-price',
        data: { label: 'Budget Objection', intent: 'objection', isObjection: true, color: '#f59e0b' },
      },
      {
        id: 'edge-rebuttal-book',
        source: 'node-rebuttal-price',
        sourceHandle: 'rebuttal-accepted',
        target: 'node-action-book',
        data: { label: 'Rebuttal Accepted', isReturn: true, color: '#10b981' },
      },
      {
        id: 'edge-branch-busy',
        source: 'node-intent-branch',
        sourceHandle: 'handle-busy',
        target: 'node-action-callback',
        data: { label: 'Busy / Call Later', intent: 'busy', color: '#3b82f6' },
      },
      {
        id: 'edge-branch-dnc',
        source: 'node-intent-branch',
        sourceHandle: 'handle-dnc',
        target: 'node-dnc-hangup',
        data: { label: 'Not Interested / Remove', intent: 'dnc', color: '#ef4444' },
      },
      {
        id: 'edge-book-hangup',
        source: 'node-action-book',
        target: 'node-success-hangup',
        data: { label: 'Booking Success', color: '#10b981' },
      },
      {
        id: 'edge-callback-hangup',
        source: 'node-action-callback',
        target: 'node-callback-hangup',
        data: { label: 'SMS Dispatched', color: '#3b82f6' },
      },
    ],
  },
  {
    id: 'healthcare-post-discharge',
    name: 'Healthcare Post-Op Follow-up',
    tagline: 'Empathetic clinical follow-up checking pain levels, medication & triage escalation',
    category: 'Healthcare & Patient',
    knowledge: {
      campaignId: 'healthcare-post-discharge',
      campaignName: 'Metro General Post-Surgical Recovery Call',
      description: 'Patient check-in 48 hours post-discharge to verify recovery, medication compliance, and escalate acute pain.',
      agentPersona: {
        name: 'Nurse Clara',
        role: 'Virtual Care Coordinator',
        company: 'Metro General Hospital',
        tone: 'empathetic',
        speakingRate: 0.92,
        voice: 'en-US-Standard-E',
      },
      leadProfile: {
        name: 'Robert Davis',
        company: 'Patient ID #MG-98102',
        phone: '+1 (555) 843-1920',
        email: 'robert.davis@example.com',
        attributes: {
          procedure: 'Laparoscopic Appendectomy',
          dischargeDate: 'Yesterday',
          attendingPhysician: 'Dr. Emily Vance',
        },
      },
      complianceNotice: 'This call is an automated health outreach from Metro General Hospital. If you are experiencing a life-threatening emergency, please hang up and call 911 immediately.',
      knowledgeItems: [],
      globalObjections: [
        {
          id: 'obj-emergency',
          trigger: 'I have severe chest pain / cannot breathe',
          response: 'Mr. Davis, please hang up immediately and call 911 or proceed to the nearest emergency room.',
          resumeFlow: false,
        },
      ],
      faqs: [
        {
          id: 'faq-pharmacy',
          question: 'Where was my prescription sent?',
          answer: 'Your discharge prescriptions were electronically sent to Walgreens on Maple Street. You can pick them up or request delivery.',
          keywords: ['prescription', 'pharmacy', 'medicine', 'medication', 'walgreens'],
        },
      ],
    },
    initialNodes: [
      {
        id: 'node-hc-greeting',
        type: 'greeting',
        position: { x: 400, y: 50 },
        data: {
          type: 'greeting',
          label: 'Patient ID & Wellness Greeting',
          description: 'Confirm identity of post-op patient',
          openingScript: 'Hello, this is Clara calling from Metro General Hospital for {{lead_name}}. Am I speaking with {{lead_name}}?',
          voiceStyle: 'Warm & empathetic',
        },
      },
      {
        id: 'node-hc-pain-check',
        type: 'question',
        position: { x: 400, y: 280 },
        data: {
          type: 'question',
          label: 'Pain Level Assessment (1-10)',
          description: 'Assess current discomfort and surgical incision pain',
          speechPrompt: 'I am glad to reach you, Robert. Dr. Vance wanted us to check in on how you are feeling today. On a scale from 1 to 10, how would you rate your pain right now?',
          variableToExtract: 'pain_score',
          allowBargeIn: true,
          maxWaitSeconds: 8,
          maxRepeats: 2,
          silencePrompt: 'Take your time, just let me know roughly from 1 to 10.',
        },
      },
      {
        id: 'node-hc-branch',
        type: 'scenarioBranch',
        position: { x: 400, y: 540 },
        data: {
          type: 'scenarioBranch',
          label: 'Triage Severity Evaluation',
          description: 'Route based on reported pain score and symptom severity',
          evaluationCriteria: 'Check if pain score is mild (1-4), moderate (5-7), or severe (8-10)',
          branches: [
            {
              id: 'branch-mild',
              label: 'Mild / Expected (1-4)',
              description: 'Normal recovery progression',
              intentKey: 'mild_pain',
              color: '#10b981',
              targetHandle: 'handle-mild',
            },
            {
              id: 'branch-severe',
              label: 'Severe / Acute (7+ or Fever)',
              description: 'Requires urgent clinical escalation',
              intentKey: 'severe_pain',
              color: '#ef4444',
              targetHandle: 'handle-severe',
            },
          ],
        },
      },
      {
        id: 'node-hc-escalate',
        type: 'action',
        position: { x: 650, y: 780 },
        data: {
          type: 'action',
          label: 'Live Nurse Transfer',
          description: 'Warm transfer directly to on-call triage nurse',
          actionType: 'live_transfer',
          actionConfig: {
            title: 'Post-Op Acute Pain Escalation',
            targetPhone: '+1 (555) 911-0199',
            crmTag: 'urgent_nurse_triage_escalation',
          },
        },
      },
      {
        id: 'node-hc-med-check',
        type: 'question',
        position: { x: 150, y: 780 },
        data: {
          type: 'question',
          label: 'Medication Adherence Check',
          description: 'Verify patient is taking prescribed antibiotic/pain meds',
          speechPrompt: 'That is encouraging to hear! Are you able to take your prescribed medications without any nausea or dizziness?',
          variableToExtract: 'medication_adherence',
          allowBargeIn: true,
          maxWaitSeconds: 6,
          maxRepeats: 2,
        },
      },
      {
        id: 'node-hc-success-end',
        type: 'hangup',
        position: { x: 150, y: 1040 },
        data: {
          type: 'hangup',
          label: 'Standard Follow-up Complete',
          description: 'Log positive recovery in EHR',
          closingScript: 'Wonderful. Keep resting, stay hydrated, and your follow-up with Dr. Vance is set for next Tuesday. Take care!',
          disposition: 'callback_scheduled',
          sendSummarySms: true,
        },
      },
      {
        id: 'node-hc-transfer-end',
        type: 'hangup',
        position: { x: 650, y: 1040 },
        data: {
          type: 'hangup',
          label: 'Transfer Connected',
          description: 'Connected to clinical staff',
          closingScript: 'I am connecting you right now to Nurse Jenkins. Please hold the line.',
          disposition: 'information_sent',
          sendSummarySms: false,
        },
      },
    ],
    initialEdges: [
      {
        id: 'edge-hc-1',
        source: 'node-hc-greeting',
        sourceHandle: 'human',
        target: 'node-hc-pain-check',
        data: { label: 'Patient Verified' },
      },
      {
        id: 'edge-hc-2',
        source: 'node-hc-pain-check',
        target: 'node-hc-branch',
        data: { label: 'Score Provided' },
      },
      {
        id: 'edge-hc-3',
        source: 'node-hc-branch',
        sourceHandle: 'handle-mild',
        target: 'node-hc-med-check',
        data: { label: 'Pain <= 5 (Normal)' },
      },
      {
        id: 'edge-hc-4',
        source: 'node-hc-branch',
        sourceHandle: 'handle-severe',
        target: 'node-hc-escalate',
        data: { label: 'Pain > 6 or Complications', intent: 'escalate' },
      },
      {
        id: 'edge-hc-5',
        source: 'node-hc-med-check',
        target: 'node-hc-success-end',
        data: { label: 'Meds Tolerated' },
      },
      {
        id: 'edge-hc-6',
        source: 'node-hc-escalate',
        target: 'node-hc-transfer-end',
        data: { label: 'Transfer Initiated' },
      },
    ],
  },
  {
    id: 'solar-home-qualification',
    name: 'Residential Solar Qualification',
    tagline: 'Qualifies homeowner status, electric utility bill threshold, and books site audit',
    category: 'Home Services & Energy',
    knowledge: {
      campaignId: 'solar-home-qualification',
      campaignName: 'SunBright Energy Federal Rebate Initiative',
      description: 'Outbound campaign reaching homeowners with average electric bills over $150/mo to book zero-down solar audits.',
      agentPersona: {
        name: 'Jordan Miller',
        role: 'Clean Energy Specialist',
        company: 'SunBright Energy',
        tone: 'friendly_professional',
        speakingRate: 1.02,
        voice: 'en-US-Standard-B',
      },
      leadProfile: {
        name: 'Michael Chang',
        company: 'Homeowner',
        phone: '+1 (555) 624-8110',
        email: 'mchang88@example.com',
        attributes: {
          address: '742 Evergreen Terrace, Springfield',
          estimatedBill: '$210/mo',
        },
      },
      complianceNotice: 'Calls are recorded for quality purposes. To opt-out at any point, simply say stop.',
      knowledgeItems: [],
      globalObjections: [
        {
          id: 'obj-cost-solar',
          trigger: 'Is solar expensive or will I have a loan?',
          response: 'Great question Michael! Under the current state clean energy initiative, qualified homeowners get zero out-of-pocket installation. You simply swap your high utility bill for a lower fixed solar bill.',
          resumeFlow: true,
        },
      ],
      faqs: [
        {
          id: 'faq-tax-credit',
          question: 'What is the federal tax credit percentage?',
          answer: 'The federal Inflation Reduction Act provides a 30% tax credit on the full installation value through 2032.',
          keywords: ['tax', 'credit', 'rebate', 'government', 'incentive'],
        },
      ],
    },
    initialNodes: [
      {
        id: 'node-sol-greeting',
        type: 'greeting',
        position: { x: 400, y: 50 },
        data: {
          type: 'greeting',
          label: 'Outbound Solar Pitch & Intro',
          description: 'Opening statement for neighborhood solar program',
          openingScript: 'Hi {{lead_name}}, this is Jordan from SunBright Energy. I am reaching out regarding the local zero-down solar rebate program in your area — do you own the property at {{address}}?',
          voiceStyle: 'Upbeat & professional',
        },
      },
      {
        id: 'node-sol-branch-owner',
        type: 'scenarioBranch',
        position: { x: 400, y: 280 },
        data: {
          type: 'scenarioBranch',
          label: 'Homeowner Verification Router',
          description: 'Ensure prospect is property owner before qualifying',
          evaluationCriteria: 'Determine whether prospect owns home or is a renter',
          branches: [
            {
              id: 'branch-owner-yes',
              label: 'Homeowner Verified',
              description: 'Yes, owns the property',
              intentKey: 'homeowner_yes',
              color: '#10b981',
              targetHandle: 'handle-owner-yes',
            },
            {
              id: 'branch-owner-no',
              label: 'Renter / Not Owner',
              description: 'Rents or not decision maker',
              intentKey: 'renter_no',
              color: '#ef4444',
              targetHandle: 'handle-owner-no',
            },
          ],
        },
      },
      {
        id: 'node-sol-bill-check',
        type: 'question',
        position: { x: 200, y: 540 },
        data: {
          type: 'question',
          label: 'Monthly Utility Bill Qualification',
          description: 'Ensure monthly electricity bill exceeds $120/mo threshold',
          speechPrompt: 'Awesome! On average, is your monthly electric bill typically over or under $130 per month?',
          variableToExtract: 'monthly_bill_range',
          allowBargeIn: true,
          maxWaitSeconds: 6,
          maxRepeats: 2,
        },
      },
      {
        id: 'node-sol-action-book',
        type: 'action',
        position: { x: 200, y: 800 },
        data: {
          type: 'action',
          label: 'Book Solar Roof Assessment',
          description: 'Dispatch solar design specialist for satellite roof analysis',
          actionType: 'calendar_booking',
          actionConfig: {
            title: 'Zero-Down Solar Assessment for {{lead_name}}',
            details: 'Address: {{address}}',
            crmTag: 'solar_qualified_inspection_booked',
          },
        },
      },
      {
        id: 'node-sol-renter-hangup',
        type: 'hangup',
        position: { x: 650, y: 540 },
        data: {
          type: 'hangup',
          label: 'Renter Disqualification',
          description: 'Politely exit as program requires property ownership',
          closingScript: 'Understood, Michael. Currently the state rebate requires property ownership. Thank you for your time and have a wonderful day!',
          disposition: 'disqualified_not_interested',
          sendSummarySms: false,
        },
      },
      {
        id: 'node-sol-success-hangup',
        type: 'hangup',
        position: { x: 200, y: 1040 },
        data: {
          type: 'hangup',
          label: 'Audit Scheduled & Close',
          description: 'Confirm appointment and text confirmation',
          closingScript: 'You are all set Michael! Our solar engineer will have your satellite roof mock-up ready for tomorrow at 2 PM. I just sent a confirmation text to {{phone}}.',
          disposition: 'meeting_booked',
          sendSummarySms: true,
        },
      },
    ],
    initialEdges: [
      {
        id: 'edge-sol-1',
        source: 'node-sol-greeting',
        sourceHandle: 'human',
        target: 'node-sol-branch-owner',
        data: { label: 'Connected' },
      },
      {
        id: 'edge-sol-2',
        source: 'node-sol-branch-owner',
        sourceHandle: 'handle-owner-yes',
        target: 'node-sol-bill-check',
        data: { label: 'Owns Home' },
      },
      {
        id: 'edge-sol-3',
        source: 'node-sol-branch-owner',
        sourceHandle: 'handle-owner-no',
        target: 'node-sol-renter-hangup',
        data: { label: 'Renter' },
      },
      {
        id: 'edge-sol-4',
        source: 'node-sol-bill-check',
        target: 'node-sol-action-book',
        data: { label: 'Bill > $130 (Qualified)' },
      },
      {
        id: 'edge-sol-5',
        source: 'node-sol-action-book',
        target: 'node-sol-success-hangup',
        data: { label: 'Audit Confirmed' },
      },
    ],
  },
];
