import { CustomFlowNode, CustomFlowEdge, CampaignKnowledge } from '../types/flow';

export interface CampaignTemplate {
  id: string;
  name: string;
  tagline: string;
  category: string;
  knowledge: CampaignKnowledge;
  initialNodes: CustomFlowNode[];
  initialEdges: CustomFlowEdge[];
}

export const CAMPAIGN_TEMPLATES: CampaignTemplate[] = [
  {
    id: 'isp-renewal-speed-upgrade',
    name: 'ISP Renewal & Speed Upgrade',
    tagline: 'Outbound renewal agent with package tiers (100, 300, 1000 Mbps), loyalty discounts & Wi-Fi 6 router upgrades',
    category: 'Telecom & ISP',
    knowledge: {
      campaignId: 'isp-renewal-speed-upgrade',
      campaignName: 'Apex Fiber Loyalty Renewal Campaign',
      description: 'Outbound renewal campaign checking subscriber usage, offering 100/300/1000 Mbps packages, 20% annual contract discounts, and complimentary Wi-Fi 6 router upgrades.',
      agentPersona: {
        name: 'Maya Lin',
        role: 'VIP Loyalty Specialist',
        company: 'Apex Fiber Internet',
        tone: 'friendly_professional',
        speakingRate: 1.0,
        voice: 'en-US-Standard-C',
      },
      leadProfile: {
        name: 'David Miller',
        company: 'Home Subscriber',
        phone: '+1 (555) 492-8831',
        email: 'david.miller@apexuser.net',
        attributes: {
          currentPlan: '100 Mbps Legacy Plan',
          monthlySpend: '$39.99/mo',
          tenure: '2 Years',
          contractStatus: 'Expiring in 21 days',
        },
      },
      complianceNotice: 'This call is recorded for service quality and account verification.',
      knowledgeItems: [
        {
          id: 'isp-plans-v1',
          title: 'Renewal plans and included equipment',
          contentType: 'product_offer',
          tags: ['renewal', 'internet', 'speed', 'router'],
          content: 'Fiber 100 Mbps is $29.99 per month with a 10% six-month loyalty discount. Ultra 300 Mbps is $49.99 per month and Gigabit 1000 Mbps is $79.99 per month; both include a complimentary Wi-Fi 6 router upgrade. Annual renewal discounts are 20% on 300 Mbps and 25% on 1 Gbps.',
          source: 'Apex Fiber renewal offer sheet',
          version: '2026.1',
          status: 'approved',
        },
        {
          id: 'isp-renewal-policy-v1',
          title: 'Renewal and equipment policy',
          contentType: 'policy',
          tags: ['renewal', 'eligibility', 'delivery', 'callback'],
          content: 'Renewal offers are available to eligible existing subscribers. Router delivery takes up to two business days after confirmation. Customers may request a self-service renewal link or a later callback.',
          source: 'Apex Fiber renewal policy',
          version: '2026.1',
          status: 'approved',
        },
      ],
      globalObjections: [
        {
          id: 'obj-ai-check',
          trigger: 'Are you a robot or real person?',
          response: "I'm Maya, an AI voice assistant from Apex Fiber! I'm calling directly because your internet plan expires next month, and I wanted to make sure you get our special renewal discount and free Wi-Fi 6 upgrade before it ends.",
          resumeFlow: true,
        },
        {
          id: 'obj-too-busy',
          trigger: 'I am busy right now',
          response: "No problem at all David! I can send our 20% discount renewal link directly to your mobile via SMS right now so you can review it whenever you have a minute. Sounds good?",
          resumeFlow: false,
        },
      ],
      faqs: [
        {
          id: 'faq-packages',
          question: 'What packages and Mbps speeds do you offer?',
          answer: 'We offer Fiber 100 Mbps at $29.99, Ultra 300 Mbps at $49.99 with free Wi-Fi 6, and Gigabit 1000 Mbps at $79.99 with up to 25% annual contract discounts!',
          keywords: ['package', 'packages', 'speed', 'speeds', 'mbps', 'plans', 'options'],
        },
        {
          id: 'faq-discounts',
          question: 'What renewal discounts are available?',
          answer: 'You get 10% off for 6 months, or 20% off annual renewal on 300 Mbps, and 25% off 1 Gbps, plus an extra $5/month discount with auto-pay!',
          keywords: ['discount', 'discounts', 'deal', 'savings', 'cheaper', 'promo', 'offer'],
        },
        {
          id: 'faq-router',
          question: 'Do I get a new router?',
          answer: 'Yes! Renewing with 300 Mbps or 1000 Mbps includes a complimentary Wi-Fi 6 smart router with zero monthly equipment rental fees.',
          keywords: ['router', 'modem', 'wifi', 'wi-fi', 'equipment', 'hardware'],
        },
      ],
    },
    initialNodes: [
      {
        id: 'node-greeting',
        type: 'greeting',
        position: { x: 380, y: 50 },
        data: {
          type: 'greeting',
          label: 'Renewal Greeting & Availability',
          description: 'Announce contract expiration & loyalty speed upgrade',
          openingScript: 'Hi {{lead_name}}, this is Maya from Apex Fiber. I am reaching out because your current internet renewal is coming up next month, and we have special loyalty discounts and speed upgrades available. Do you have just a minute?',
          voiceStyle: 'Warm & helpful',
        },
      },
      {
        id: 'node-q2-usage',
        type: 'question',
        position: { x: 380, y: 220 },
        data: {
          type: 'question',
          label: 'Step 2: Household Usage Discovery',
          description: 'Discover customer streaming, work, and device requirements',
          speechPrompt: 'Awesome! Are you mainly using the internet for basic browsing and email, or do you have multiple people working from home and streaming 4K video?',
          allowBargeIn: true,
          maxWaitSeconds: 5,
        },
      },
      {
        id: 'node-q3-basic',
        type: 'question',
        position: { x: 160, y: 400 },
        data: {
          type: 'question',
          label: 'Step 3A: Fiber 100 Mbps Plan',
          description: 'For light usage: 100 Mbps @ $29.99/mo',
          speechPrompt: 'Understood! For lighter usage, our Fiber 100 Mbps plan is just $29.99 a month with a 10% loyalty discount. Would you like me to lock in this renewal rate for you today?',
          allowBargeIn: true,
          maxWaitSeconds: 5,
        },
      },
      {
        id: 'node-q4-highspeed',
        type: 'question',
        position: { x: 600, y: 400 },
        data: {
          type: 'question',
          label: 'Step 3B: Ultra 300 & Gigabit 1000 Mbps',
          description: 'For heavy streaming: 300 Mbps or 1 Gbps with Wi-Fi 6 router',
          speechPrompt: 'Got it! For heavy streaming and remote work, our Ultra 300 Mbps is $49.99/mo, or Gigabit 1000 Mbps at $79.99/mo. Both include a free Wi-Fi 6 router upgrade and 20% annual discount. Which speed fits your home best?',
          allowBargeIn: true,
          maxWaitSeconds: 5,
        },
      },
      {
        id: 'node-rebuttal-cost',
        type: 'knowledge',
        position: { x: 380, y: 580 },
        data: {
          type: 'knowledge',
          label: 'Cost & Discount Rebuttal',
          description: 'Highlight 20% annual savings + free router upgrade',
          objectionTopic: 'Price & Monthly Bill Concern',
          rebuttalScript: 'I completely understand keeping bills down! With our 20% annual renewal discount, you actually save $180 a year compared to standard rates, and the Wi-Fi 6 router is included with zero rental fees. Shall I lock that savings in for you?',
          returnToPrevious: true,
        },
      },
      {
        id: 'node-action-confirm',
        type: 'action',
        position: { x: 380, y: 760 },
        data: {
          type: 'action',
          label: 'Lock In Renewal & Dispatch Wi-Fi 6',
          description: 'Commit renewal, apply 20% discount, dispatch hardware kit',
          actionType: 'calendar_booking',
          actionConfig: {
            title: 'Internet Renewal Confirmed - Wi-Fi 6 Kit Dispatched',
            details: 'Apex Fiber 300 Mbps Plan @ $49.99/mo with 20% discount applied.',
          },
        },
      },
      {
        id: 'node-hangup-declined',
        type: 'hangup',
        position: { x: -80, y: 320 },
        data: {
          type: 'hangup',
          label: 'Polite Exit & SMS Dispatch',
          description: 'Graceful opt-out and follow-up link sent',
          closingScript: 'No problem at all {{lead_name}}. I will text you the renewal self-service link so you have it handy before your plan expires. Have a wonderful day!',
          disposition: 'callback_scheduled',
          sendSummarySms: true,
        },
      },
      {
        id: 'node-hangup-success',
        type: 'hangup',
        position: { x: 380, y: 920 },
        data: {
          type: 'hangup',
          label: 'Renewal Complete & Wrap-up',
          description: 'Congratulate subscriber and conclude call',
          closingScript: 'You are all set, {{lead_name}}! Your renewal discount is locked in, and your new Wi-Fi 6 router will arrive in 2 business days. Thank you for staying with Apex Fiber!',
          disposition: 'meeting_booked',
          sendSummarySms: true,
        },
      },
    ],
    initialEdges: [
      {
        id: 'edge-greet-q2',
        source: 'node-greeting',
        target: 'node-q2-usage',
        type: 'custom',
        data: { label: 'Customer Available / Yes' },
      },
      {
        id: 'edge-greet-exit',
        source: 'node-greeting',
        target: 'node-hangup-declined',
        type: 'custom',
        data: { label: 'Busy / Not Interested' },
      },
      {
        id: 'edge-q2-to-q3',
        source: 'node-q2-usage',
        target: 'node-q3-basic',
        type: 'custom',
        data: { label: 'If Light Usage / 1-2 Users -> Q3 (100 Mbps)' },
      },
      {
        id: 'edge-q2-to-q4',
        source: 'node-q2-usage',
        target: 'node-q4-highspeed',
        type: 'custom',
        data: { label: 'If Heavy Streaming / Work -> Q4 (300/1000 Mbps)' },
      },
      {
        id: 'edge-q2-to-rebuttal',
        source: 'node-q2-usage',
        target: 'node-rebuttal-cost',
        type: 'custom',
        data: { label: 'If Price Objection -> Rebuttal', isObjection: true },
      },
      {
        id: 'edge-q3-to-action',
        source: 'node-q3-basic',
        target: 'node-action-confirm',
        type: 'custom',
        data: { label: 'If Agrees to 100 Mbps -> Confirm' },
      },
      {
        id: 'edge-q3-to-rebuttal',
        source: 'node-q3-basic',
        target: 'node-rebuttal-cost',
        type: 'custom',
        data: { label: 'If Price Objection -> Rebuttal', isObjection: true },
      },
      {
        id: 'edge-q4-to-action',
        source: 'node-q4-highspeed',
        target: 'node-action-confirm',
        type: 'custom',
        data: { label: 'If Chooses 300 or 1000 Mbps -> Confirm' },
      },
      {
        id: 'edge-q4-to-rebuttal',
        source: 'node-q4-highspeed',
        target: 'node-rebuttal-cost',
        type: 'custom',
        data: { label: 'If Too Expensive -> Rebuttal', isObjection: true },
      },
      {
        id: 'edge-rebuttal-to-action',
        source: 'node-rebuttal-cost',
        target: 'node-action-confirm',
        type: 'custom',
        data: { label: 'If Agrees After Discount -> Confirm' },
      },
      {
        id: 'edge-action-to-success',
        source: 'node-action-confirm',
        target: 'node-hangup-success',
        type: 'custom',
        data: { label: 'Complete Renewal' },
      },
    ],
  },
  {
    id: 'b2b-saas-qualification',
    name: 'B2B SaaS Demo Qualification',
    tagline: 'High-converting outbound SDR agent with objection rebuttals & calendar booking',
    category: 'Sales & SDR',
    knowledge: {
      campaignId: 'b2b-saas-qualification',
      campaignName: 'DataPilot Cloud Optimizer SDR Outreach',
      description: 'Outbound campaign targeting VP/Director of Engineering to qualify and schedule 15-min live architecture demos.',
      agentPersona: {
        name: 'Sarah Chen',
        role: 'Senior Solutions Specialist',
        company: 'DataPilot AI',
        tone: 'consultative',
        speakingRate: 1.0,
        voice: 'en-US-Standard-C',
      },
      leadProfile: {
        name: 'Alex Mercer',
        company: 'Apex Logistics',
        phone: '+1 (555) 382-9912',
        email: 'alex.mercer@apexlogistics.io',
        attributes: {
          role: 'Head of Infrastructure',
          cloudProvider: 'AWS & Kubernetes',
          estimatedSpend: '$45,000/mo',
        },
      },
      complianceNotice: 'This call is recorded for quality assurance and training purposes.',
      knowledgeItems: [],
      globalObjections: [
        {
          id: 'obj-ai-check',
          trigger: 'Are you an AI or a real person?',
          response: "I'm Sarah, an AI voice assistant from DataPilot! I'm reaching out directly to see if exploring automated AWS cost reduction makes sense for your team before looping in our lead engineer.",
          resumeFlow: true,
        },
        {
          id: 'obj-how-got-number',
          trigger: 'How did you get my number?',
          response: 'Your contact was listed in our verified B2B infrastructure directory for Apex Logistics engineering leadership. I apologize if this caught you at an inconvenient time!',
          resumeFlow: true,
        },
      ],
      faqs: [
        {
          id: 'faq-pricing',
          question: 'How much does DataPilot cost?',
          answer: 'We operate on a pure performance model — zero upfront software fee, taking only 15% of the net savings verified on your monthly cloud invoice.',
          keywords: ['cost', 'price', 'pricing', 'expensive', 'fee'],
        },
        {
          id: 'faq-security',
          question: 'Is it SOC2 compliant and safe for production clusters?',
          answer: 'Yes, we are SOC 2 Type II certified and read-only by default. We never access user data or application payloads.',
          keywords: ['security', 'soc2', 'safe', 'compliance', 'safe'],
        },
      ],
    },
    initialNodes: [
      {
        id: 'node-greeting',
        type: 'greeting',
        position: { x: 400, y: 50 },
        data: {
          type: 'greeting',
          label: 'Outbound Greeting',
          description: 'Initial greeting with prospect',
          openingScript: 'Hi {{lead_name}}, this is Sarah from DataPilot. I noticed your team at {{company}} is managing Kubernetes workloads — do you have 30 seconds?',
          voiceStyle: 'Friendly & confident',
          gatekeeperHandling: 'I am calling to follow up with Alex regarding Apex Logistics cloud optimization project.',
        },
      },
      {
        id: 'node-value-pitch',
        type: 'question',
        position: { x: 650, y: 280 },
        data: {
          type: 'question',
          label: 'Value Hook & Discovery',
          description: 'Introduce automated savings and test initiative priority',
          speechPrompt: 'Awesome! We help DevOps teams automatically trim 30% off EC2 and container spend without modifying code. Is cloud efficiency or cluster scaling an active priority this quarter?',
          variableToExtract: 'cloud_priority',
          allowBargeIn: true,
          maxWaitSeconds: 6,
          silencePrompt: 'Just wanted to check if you can hear me OK?',
        },
      },
      {
        id: 'node-intent-branch',
        type: 'scenarioBranch',
        position: { x: 650, y: 540 },
        data: {
          type: 'scenarioBranch',
          label: 'Lead Intent Router',
          description: 'Branch dynamically based on prospect sentiment and objections',
          evaluationCriteria: 'Analyze caller response for interest, budget objection, timing constraint, or flat refusal',
          branches: [
            {
              id: 'branch-positive',
              label: 'Positive / Interested',
              description: 'Prospect confirms interest or expresses pain point',
              intentKey: 'positive_interest',
              color: '#10b981',
              targetHandle: 'handle-pos',
            },
            {
              id: 'branch-price',
              label: 'Budget / Price Objection',
              description: 'Mentions lack of budget or cost worries',
              intentKey: 'price_objection',
              color: '#f59e0b',
              targetHandle: 'handle-price',
            },
            {
              id: 'branch-busy',
              label: 'Busy / Driving / Callback',
              description: 'Requests callback or is in middle of meeting',
              intentKey: 'timing_busy',
              color: '#3b82f6',
              targetHandle: 'handle-busy',
            },
            {
              id: 'branch-dnc',
              label: 'Not Interested / DNC',
              description: 'Direct rejection or remove from list',
              intentKey: 'not_interested',
              color: '#ef4444',
              targetHandle: 'handle-dnc',
            },
          ],
        },
      },
      {
        id: 'node-rebuttal-price',
        type: 'knowledge',
        position: { x: 250, y: 780 },
        data: {
          type: 'knowledge',
          label: 'Budget Objection Rebuttal',
          description: 'Clarify performance-only model and loop back',
          category: 'Objection Handling',
          objectionTopic: 'No Budget Available',
          rebuttalScript: 'Totally understand budget freezes! That is actually why our model requires zero software budget — we only take a percentage of the actual cloud savings we prove on your AWS bill. Does a 15-minute review with our systems architect sound unreasonable?',
          returnToPrevious: true,
          followUpPrompt: 'Would Tuesday or Thursday morning work better for you?',
        },
      },
      {
        id: 'node-action-book',
        type: 'action',
        position: { x: 750, y: 800 },
        data: {
          type: 'action',
          label: 'Book Demo Slot',
          description: 'Trigger calendar webhook and lock appointment slot',
          actionType: 'calendar_booking',
          actionConfig: {
            title: '15-Min Cloud Optimization Audit with DataPilot',
            details: 'Invitee: {{lead_name}} ({{company}})',
            targetPhone: '{{phone}}',
            crmTag: 'lead_qualified_demo_booked',
          },
        },
      },
      {
        id: 'node-action-callback',
        type: 'action',
        position: { x: 1150, y: 780 },
        data: {
          type: 'action',
          label: 'Dispatch SMS Callback',
          description: 'Send self-scheduling calendar link via SMS',
          actionType: 'send_sms',
          actionConfig: {
            title: 'DataPilot Scheduling Link',
            details: 'Hi {{lead_name}}, as discussed, here is the link to grab 10 mins whenever convenient: cal.datapilot.ai/demo',
            crmTag: 'callback_requested_sms_sent',
          },
        },
      },
      {
        id: 'node-success-hangup',
        type: 'hangup',
        position: { x: 750, y: 1040 },
        data: {
          type: 'hangup',
          label: 'Demo Confirmed & Wrap Up',
          description: 'Thank the caller and send calendar invite',
          closingScript: "You're all set, {{lead_name}}! You will receive an invite from our principal engineer for Thursday at 10 AM. Thanks for your time and have a productive day!",
          disposition: 'meeting_booked',
          sendSummarySms: true,
        },
      },
      {
        id: 'node-callback-hangup',
        type: 'hangup',
        position: { x: 1150, y: 1040 },
        data: {
          type: 'hangup',
          label: 'Callback Scheduled Wrap Up',
          description: 'Polite close for busy lead',
          closingScript: 'Just texted the direct link to {{phone}}. Look forward to connecting later. Have a wonderful rest of your day!',
          disposition: 'callback_scheduled',
          sendSummarySms: true,
        },
      },
      {
        id: 'node-dnc-hangup',
        type: 'hangup',
        position: { x: 1450, y: 780 },
        data: {
          type: 'hangup',
          label: 'Polite DNC Disconnect',
          description: 'Honor opt-out request and tag CRM',
          closingScript: 'No problem at all. I have noted your preference and removed your number from our outreach. Thank you for your time.',
          disposition: 'dnc_requested',
          sendSummarySms: false,
        },
      },
    ],
    initialEdges: [
      {
        id: 'edge-greeting-human',
        source: 'node-greeting',
        sourceHandle: 'human',
        target: 'node-value-pitch',
        data: { label: 'Human Answered', intent: 'human_connected' },
      },
      {
        id: 'edge-pitch-branch',
        source: 'node-value-pitch',
        target: 'node-intent-branch',
        data: { label: 'Caller Responds' },
      },
      {
        id: 'edge-branch-pos',
        source: 'node-intent-branch',
        sourceHandle: 'handle-pos',
        target: 'node-action-book',
        data: { label: 'Interested / Needs Savings', intent: 'positive' },
      },
      {
        id: 'edge-branch-price',
        source: 'node-intent-branch',
        sourceHandle: 'handle-price',
        target: 'node-rebuttal-price',
        data: { label: 'Budget Objection', intent: 'objection', isObjection: true },
      },
      {
        id: 'edge-rebuttal-book',
        source: 'node-rebuttal-price',
        sourceHandle: 'rebuttal-accepted',
        target: 'node-action-book',
        data: { label: 'Rebuttal Accepted' },
      },
      {
        id: 'edge-branch-busy',
        source: 'node-intent-branch',
        sourceHandle: 'handle-busy',
        target: 'node-action-callback',
        data: { label: 'Busy / Call Later', intent: 'busy' },
      },
      {
        id: 'edge-branch-dnc',
        source: 'node-intent-branch',
        sourceHandle: 'handle-dnc',
        target: 'node-dnc-hangup',
        data: { label: 'Not Interested / Remove', intent: 'dnc' },
      },
      {
        id: 'edge-book-hangup',
        source: 'node-action-book',
        target: 'node-success-hangup',
        data: { label: 'Booking Success' },
      },
      {
        id: 'edge-callback-hangup',
        source: 'node-action-callback',
        target: 'node-callback-hangup',
        data: { label: 'SMS Dispatched' },
      },
    ],
  },
  {
    id: 'healthcare-post-discharge',
    name: 'Healthcare Post-Op Follow-up',
    tagline: 'Empathetic clinical follow-up checking pain levels, medication & triage escalation',
    category: 'Healthcare & Patient',
    knowledge: {
      campaignId: 'healthcare-post-discharge',
      campaignName: 'Metro General Post-Surgical Recovery Call',
      description: 'Patient check-in 48 hours post-discharge to verify recovery, medication compliance, and escalate acute pain.',
      agentPersona: {
        name: 'Nurse Clara',
        role: 'Virtual Care Coordinator',
        company: 'Metro General Hospital',
        tone: 'empathetic',
        speakingRate: 0.92,
        voice: 'en-US-Standard-E',
      },
      leadProfile: {
        name: 'Robert Davis',
        company: 'Patient ID #MG-98102',
        phone: '+1 (555) 843-1920',
        email: 'robert.davis@example.com',
        attributes: {
          procedure: 'Laparoscopic Appendectomy',
          dischargeDate: 'Yesterday',
          attendingPhysician: 'Dr. Emily Vance',
        },
      },
      complianceNotice: 'This call is an automated health outreach from Metro General Hospital. If you are experiencing a life-threatening emergency, please hang up and call 911 immediately.',
      knowledgeItems: [],
      globalObjections: [
        {
          id: 'obj-emergency',
          trigger: 'I have severe chest pain / cannot breathe',
          response: 'Mr. Davis, please hang up immediately and call 911 or proceed to the nearest emergency room.',
          resumeFlow: false,
        },
      ],
      faqs: [
        {
          id: 'faq-pharmacy',
          question: 'Where was my prescription sent?',
          answer: 'Your discharge prescriptions were electronically sent to Walgreens on Maple Street. You can pick them up or request delivery.',
          keywords: ['prescription', 'pharmacy', 'medicine', 'medication', 'walgreens'],
        },
      ],
    },
    initialNodes: [
      {
        id: 'node-hc-greeting',
        type: 'greeting',
        position: { x: 400, y: 50 },
        data: {
          type: 'greeting',
          label: 'Patient ID & Wellness Greeting',
          description: 'Confirm identity of post-op patient',
          openingScript: 'Hello, this is Clara calling from Metro General Hospital for {{lead_name}}. Am I speaking with {{lead_name}}?',
          voiceStyle: 'Warm & empathetic',
        },
      },
      {
        id: 'node-hc-pain-check',
        type: 'question',
        position: { x: 400, y: 280 },
        data: {
          type: 'question',
          label: 'Pain Level Assessment (1-10)',
          description: 'Assess current discomfort and surgical incision pain',
          speechPrompt: 'I am glad to reach you, Robert. Dr. Vance wanted us to check in on how you are feeling today. On a scale from 1 to 10, how would you rate your pain right now?',
          variableToExtract: 'pain_score',
          allowBargeIn: true,
          maxWaitSeconds: 8,
          silencePrompt: 'Take your time, just let me know roughly from 1 to 10.',
        },
      },
      {
        id: 'node-hc-branch',
        type: 'scenarioBranch',
        position: { x: 400, y: 540 },
        data: {
          type: 'scenarioBranch',
          label: 'Triage Severity Evaluation',
          description: 'Route based on reported pain score and symptom severity',
          evaluationCriteria: 'Check if pain score is mild (1-4), moderate (5-7), or severe (8-10)',
          branches: [
            {
              id: 'branch-mild',
              label: 'Mild / Expected (1-4)',
              description: 'Normal recovery progression',
              intentKey: 'mild_pain',
              color: '#10b981',
              targetHandle: 'handle-mild',
            },
            {
              id: 'branch-severe',
              label: 'Severe / Acute (7+ or Fever)',
              description: 'Requires urgent clinical escalation',
              intentKey: 'severe_pain',
              color: '#ef4444',
              targetHandle: 'handle-severe',
            },
          ],
        },
      },
      {
        id: 'node-hc-escalate',
        type: 'action',
        position: { x: 650, y: 780 },
        data: {
          type: 'action',
          label: 'Live Nurse Transfer',
          description: 'Warm transfer directly to on-call triage nurse',
          actionType: 'live_transfer',
          actionConfig: {
            title: 'Post-Op Acute Pain Escalation',
            targetPhone: '+1 (555) 911-0199',
            crmTag: 'urgent_nurse_triage_escalation',
          },
        },
      },
      {
        id: 'node-hc-med-check',
        type: 'question',
        position: { x: 150, y: 780 },
        data: {
          type: 'question',
          label: 'Medication Adherence Check',
          description: 'Verify patient is taking prescribed antibiotic/pain meds',
          speechPrompt: 'That is encouraging to hear! Are you able to take your prescribed medications without any nausea or dizziness?',
          variableToExtract: 'medication_adherence',
          allowBargeIn: true,
          maxWaitSeconds: 6,
        },
      },
      {
        id: 'node-hc-success-end',
        type: 'hangup',
        position: { x: 150, y: 1040 },
        data: {
          type: 'hangup',
          label: 'Standard Follow-up Complete',
          description: 'Log positive recovery in EHR',
          closingScript: 'Wonderful. Keep resting, stay hydrated, and your follow-up with Dr. Vance is set for next Tuesday. Take care!',
          disposition: 'callback_scheduled',
          sendSummarySms: true,
        },
      },
      {
        id: 'node-hc-transfer-end',
        type: 'hangup',
        position: { x: 650, y: 1040 },
        data: {
          type: 'hangup',
          label: 'Transfer Connected',
          description: 'Connected to clinical staff',
          closingScript: 'I am connecting you right now to Nurse Jenkins. Please hold the line.',
          disposition: 'information_sent',
          sendSummarySms: false,
        },
      },
    ],
    initialEdges: [
      {
        id: 'edge-hc-1',
        source: 'node-hc-greeting',
        sourceHandle: 'human',
        target: 'node-hc-pain-check',
        data: { label: 'Patient Verified' },
      },
      {
        id: 'edge-hc-2',
        source: 'node-hc-pain-check',
        target: 'node-hc-branch',
        data: { label: 'Score Provided' },
      },
      {
        id: 'edge-hc-3',
        source: 'node-hc-branch',
        sourceHandle: 'handle-mild',
        target: 'node-hc-med-check',
        data: { label: 'Pain <= 5 (Normal)' },
      },
      {
        id: 'edge-hc-4',
        source: 'node-hc-branch',
        sourceHandle: 'handle-severe',
        target: 'node-hc-escalate',
        data: { label: 'Pain > 6 or Complications', intent: 'escalate' },
      },
      {
        id: 'edge-hc-5',
        source: 'node-hc-med-check',
        target: 'node-hc-success-end',
        data: { label: 'Meds Tolerated' },
      },
      {
        id: 'edge-hc-6',
        source: 'node-hc-escalate',
        target: 'node-hc-transfer-end',
        data: { label: 'Transfer Initiated' },
      },
    ],
  },
  {
    id: 'solar-home-qualification',
    name: 'Residential Solar Qualification',
    tagline: 'Qualifies homeowner status, electric utility bill threshold, and books site audit',
    category: 'Home Services & Energy',
    knowledge: {
      campaignId: 'solar-home-qualification',
      campaignName: 'SunBright Energy Federal Rebate Initiative',
      description: 'Outbound campaign reaching homeowners with average electric bills over $150/mo to book zero-down solar audits.',
      agentPersona: {
        name: 'Jordan Miller',
        role: 'Clean Energy Specialist',
        company: 'SunBright Energy',
        tone: 'friendly_professional',
        speakingRate: 1.02,
        voice: 'en-US-Standard-B',
      },
      leadProfile: {
        name: 'Michael Chang',
        company: 'Homeowner',
        phone: '+1 (555) 624-8110',
        email: 'mchang88@example.com',
        attributes: {
          address: '742 Evergreen Terrace, Springfield',
          estimatedBill: '$210/mo',
        },
      },
      complianceNotice: 'Calls are recorded for quality purposes. To opt-out at any point, simply say stop.',
      knowledgeItems: [],
      globalObjections: [
        {
          id: 'obj-cost-solar',
          trigger: 'Is solar expensive or will I have a loan?',
          response: 'Great question Michael! Under the current state clean energy initiative, qualified homeowners get zero out-of-pocket installation. You simply swap your high utility bill for a lower fixed solar bill.',
          resumeFlow: true,
        },
      ],
      faqs: [
        {
          id: 'faq-tax-credit',
          question: 'What is the federal tax credit percentage?',
          answer: 'The federal Inflation Reduction Act provides a 30% tax credit on the full installation value through 2032.',
          keywords: ['tax', 'credit', 'rebate', 'government', 'incentive'],
        },
      ],
    },
    initialNodes: [
      {
        id: 'node-sol-greeting',
        type: 'greeting',
        position: { x: 400, y: 50 },
        data: {
          type: 'greeting',
          label: 'Outbound Solar Pitch & Intro',
          description: 'Opening statement for neighborhood solar program',
          openingScript: 'Hi {{lead_name}}, this is Jordan from SunBright Energy. I am reaching out regarding the local zero-down solar rebate program in your area — do you own the property at {{address}}?',
          voiceStyle: 'Upbeat & professional',
        },
      },
      {
        id: 'node-sol-branch-owner',
        type: 'scenarioBranch',
        position: { x: 400, y: 280 },
        data: {
          type: 'scenarioBranch',
          label: 'Homeowner Verification Router',
          description: 'Ensure prospect is property owner before qualifying',
          evaluationCriteria: 'Determine whether prospect owns home or is a renter',
          branches: [
            {
              id: 'branch-owner-yes',
              label: 'Homeowner Verified',
              description: 'Yes, owns the property',
              intentKey: 'homeowner_yes',
              color: '#10b981',
              targetHandle: 'handle-owner-yes',
            },
            {
              id: 'branch-owner-no',
              label: 'Renter / Not Owner',
              description: 'Rents or not decision maker',
              intentKey: 'renter_no',
              color: '#ef4444',
              targetHandle: 'handle-owner-no',
            },
          ],
        },
      },
      {
        id: 'node-sol-bill-check',
        type: 'question',
        position: { x: 200, y: 540 },
        data: {
          type: 'question',
          label: 'Monthly Utility Bill Qualification',
          description: 'Ensure monthly electricity bill exceeds $120/mo threshold',
          speechPrompt: 'Awesome! On average, is your monthly electric bill typically over or under $130 per month?',
          variableToExtract: 'monthly_bill_range',
          allowBargeIn: true,
          maxWaitSeconds: 6,
        },
      },
      {
        id: 'node-sol-action-book',
        type: 'action',
        position: { x: 200, y: 800 },
        data: {
          type: 'action',
          label: 'Book Solar Roof Assessment',
          description: 'Dispatch solar design specialist for satellite roof analysis',
          actionType: 'calendar_booking',
          actionConfig: {
            title: 'Zero-Down Solar Assessment for {{lead_name}}',
            details: 'Address: {{address}}',
            crmTag: 'solar_qualified_inspection_booked',
          },
        },
      },
      {
        id: 'node-sol-renter-hangup',
        type: 'hangup',
        position: { x: 650, y: 540 },
        data: {
          type: 'hangup',
          label: 'Renter Disqualification',
          description: 'Politely exit as program requires property ownership',
          closingScript: 'Understood, Michael. Currently the state rebate requires property ownership. Thank you for your time and have a wonderful day!',
          disposition: 'disqualified_not_interested',
          sendSummarySms: false,
        },
      },
      {
        id: 'node-sol-success-hangup',
        type: 'hangup',
        position: { x: 200, y: 1040 },
        data: {
          type: 'hangup',
          label: 'Audit Scheduled & Close',
          description: 'Confirm appointment and text confirmation',
          closingScript: 'You are all set Michael! Our solar engineer will have your satellite roof mock-up ready for tomorrow at 2 PM. I just sent a confirmation text to {{phone}}.',
          disposition: 'meeting_booked',
          sendSummarySms: true,
        },
      },
    ],
    initialEdges: [
      {
        id: 'edge-sol-1',
        source: 'node-sol-greeting',
        sourceHandle: 'human',
        target: 'node-sol-branch-owner',
        data: { label: 'Connected' },
      },
      {
        id: 'edge-sol-2',
        source: 'node-sol-branch-owner',
        sourceHandle: 'handle-owner-yes',
        target: 'node-sol-bill-check',
        data: { label: 'Owns Home' },
      },
      {
        id: 'edge-sol-3',
        source: 'node-sol-branch-owner',
        sourceHandle: 'handle-owner-no',
        target: 'node-sol-renter-hangup',
        data: { label: 'Renter' },
      },
      {
        id: 'edge-sol-4',
        source: 'node-sol-bill-check',
        target: 'node-sol-action-book',
        data: { label: 'Bill > $130 (Qualified)' },
      },
      {
        id: 'edge-sol-5',
        source: 'node-sol-action-book',
        target: 'node-sol-success-hangup',
        data: { label: 'Audit Confirmed' },
      },
    ],
  },
];
