import { CustomFlowNode, CustomFlowEdge, CampaignKnowledge } from '../types/flow';

export interface CampaignTemplate {
  id: string;
  name: string;
  tagline: string;
  category: string;
  knowledge: CampaignKnowledge;
  initialNodes: CustomFlowNode[];
  initialEdges: CustomFlowEdge[];
}

export const CAMPAIGN_TEMPLATES: CampaignTemplate[] = [
  {
    id: 'b2b-saas-qualification',
    name: 'B2B SaaS Demo Qualification',
    tagline: 'High-converting outbound SDR agent with objection rebuttals & calendar booking',
    category: 'Sales & SDR',
    knowledge: {
      campaignId: 'b2b-saas-qualification',
      campaignName: 'DataPilot Cloud Optimizer SDR Outreach',
      description: 'Outbound campaign targeting VP/Director of Engineering to qualify and schedule 15-min live architecture demos.',
      agentPersona: {
        name: 'Sarah Chen',
        role: 'Senior Solutions Specialist',
        company: 'DataPilot AI',
        tone: 'consultative',
        speakingRate: 1.0,
        voice: 'en-US-Standard-C',
      },
      leadProfile: {
        name: 'Alex Mercer',
        company: 'Apex Logistics',
        phone: '+1 (555) 382-9912',
        email: 'alex.mercer@apexlogistics.io',
        attributes: {
          role: 'Head of Infrastructure',
          cloudProvider: 'AWS & Kubernetes',
          estimatedSpend: '$45,000/mo',
        },
      },
      complianceNotice: 'This call is recorded for quality assurance and training purposes.',
      globalObjections: [
        {
          id: 'obj-ai-check',
          trigger: 'Are you an AI or a real person?',
          response: "I'm Sarah, an AI voice assistant from DataPilot! I'm reaching out directly to see if exploring automated AWS cost reduction makes sense for your team before looping in our lead engineer.",
          resumeFlow: true,
        },
        {
          id: 'obj-how-got-number',
          trigger: 'How did you get my number?',
          response: 'Your contact was listed in our verified B2B infrastructure directory for Apex Logistics engineering leadership. I apologize if this caught you at an inconvenient time!',
          resumeFlow: true,
        },
      ],
      faqs: [
        {
          id: 'faq-pricing',
          question: 'How much does DataPilot cost?',
          answer: 'We operate on a pure performance model — zero upfront software fee, taking only 15% of the net savings verified on your monthly cloud invoice.',
          keywords: ['cost', 'price', 'pricing', 'expensive', 'fee'],
        },
        {
          id: 'faq-security',
          question: 'Is it SOC2 compliant and safe for production clusters?',
          answer: 'Yes, we are SOC 2 Type II certified and read-only by default. We never access user data or application payloads.',
          keywords: ['security', 'soc2', 'safe', 'compliance', 'safe'],
        },
      ],
    },
    initialNodes: [
      {
        id: 'node-greeting',
        type: 'greeting',
        position: { x: 400, y: 50 },
        data: {
          type: 'greeting',
          label: 'Outbound Greeting & AMD',
          description: 'Initial greeting with voicemail & gatekeeper detection',
          openingScript: 'Hi {{lead_name}}, this is Sarah from DataPilot. I noticed your team at {{company}} is managing Kubernetes workloads — do you have 30 seconds?',
          voiceStyle: 'Friendly & confident',
          enableAmd: true,
          voicemailScript: 'Hi {{lead_name}}, Alex here with DataPilot. Following up on your cloud infrastructure. I will drop a note to your email. Have a great day!',
          gatekeeperHandling: 'I am calling to follow up with Alex regarding Apex Logistics cloud optimization project.',
        },
      },
      {
        id: 'node-vm-hangup',
        type: 'hangup',
        position: { x: 100, y: 320 },
        data: {
          type: 'hangup',
          label: 'Voicemail Drop & End',
          description: 'Dropped voicemail audio and tagged for email follow-up',
          closingScript: 'Leaving voicemail message and sending automated follow-up email.',
          disposition: 'voicemail_left',
          sendSummarySms: true,
        },
      },
      {
        id: 'node-value-pitch',
        type: 'question',
        position: { x: 650, y: 280 },
        data: {
          type: 'question',
          label: 'Value Hook & Discovery',
          description: 'Introduce automated savings and test initiative priority',
          speechPrompt: 'Awesome! We help DevOps teams automatically trim 30% off EC2 and container spend without modifying code. Is cloud efficiency or cluster scaling an active priority this quarter?',
          variableToExtract: 'cloud_priority',
          allowBargeIn: true,
          maxWaitSeconds: 6,
          silencePrompt: 'Just wanted to check if you can hear me OK?',
        },
      },
      {
        id: 'node-intent-branch',
        type: 'scenarioBranch',
        position: { x: 650, y: 540 },
        data: {
          type: 'scenarioBranch',
          label: 'Lead Intent Router',
          description: 'Branch dynamically based on prospect sentiment and objections',
          evaluationCriteria: 'Analyze caller response for interest, budget objection, timing constraint, or flat refusal',
          branches: [
            {
              id: 'branch-positive',
              label: 'Positive / Interested',
              description: 'Prospect confirms interest or expresses pain point',
              intentKey: 'positive_interest',
              color: '#10b981',
              targetHandle: 'handle-pos',
            },
            {
              id: 'branch-price',
              label: 'Budget / Price Objection',
              description: 'Mentions lack of budget or cost worries',
              intentKey: 'price_objection',
              color: '#f59e0b',
              targetHandle: 'handle-price',
            },
            {
              id: 'branch-busy',
              label: 'Busy / Driving / Callback',
              description: 'Requests callback or is in middle of meeting',
              intentKey: 'timing_busy',
              color: '#3b82f6',
              targetHandle: 'handle-busy',
            },
            {
              id: 'branch-dnc',
              label: 'Not Interested / DNC',
              description: 'Direct rejection or remove from list',
              intentKey: 'not_interested',
              color: '#ef4444',
              targetHandle: 'handle-dnc',
            },
          ],
        },
      },
      {
        id: 'node-rebuttal-price',
        type: 'knowledge',
        position: { x: 250, y: 780 },
        data: {
          type: 'knowledge',
          label: 'Budget Objection Rebuttal',
          description: 'Clarify performance-only model and loop back',
          category: 'Objection Handling',
          objectionTopic: 'No Budget Available',
          rebuttalScript: 'Totally understand budget freezes! That is actually why our model requires zero software budget — we only take a percentage of the actual cloud savings we prove on your AWS bill. Does a 15-minute review with our systems architect sound unreasonable?',
          returnToPrevious: true,
          followUpPrompt: 'Would Tuesday or Thursday morning work better for you?',
        },
      },
      {
        id: 'node-action-book',
        type: 'action',
        position: { x: 750, y: 800 },
        data: {
          type: 'action',
          label: 'Book Demo Slot',
          description: 'Trigger calendar webhook and lock appointment slot',
          actionType: 'calendar_booking',
          actionConfig: {
            title: '15-Min Cloud Optimization Audit with DataPilot',
            details: 'Invitee: {{lead_name}} ({{company}})',
            targetPhone: '{{phone}}',
            crmTag: 'lead_qualified_demo_booked',
          },
        },
      },
      {
        id: 'node-action-callback',
        type: 'action',
        position: { x: 1150, y: 780 },
        data: {
          type: 'action',
          label: 'Dispatch SMS Callback',
          description: 'Send self-scheduling calendar link via SMS',
          actionType: 'send_sms',
          actionConfig: {
            title: 'DataPilot Scheduling Link',
            details: 'Hi {{lead_name}}, as discussed, here is the link to grab 10 mins whenever convenient: cal.datapilot.ai/demo',
            crmTag: 'callback_requested_sms_sent',
          },
        },
      },
      {
        id: 'node-success-hangup',
        type: 'hangup',
        position: { x: 750, y: 1040 },
        data: {
          type: 'hangup',
          label: 'Demo Confirmed & Wrap Up',
          description: 'Thank the caller and send calendar invite',
          closingScript: "You're all set, {{lead_name}}! You will receive an invite from our principal engineer for Thursday at 10 AM. Thanks for your time and have a productive day!",
          disposition: 'meeting_booked',
          sendSummarySms: true,
        },
      },
      {
        id: 'node-callback-hangup',
        type: 'hangup',
        position: { x: 1150, y: 1040 },
        data: {
          type: 'hangup',
          label: 'Callback Scheduled Wrap Up',
          description: 'Polite close for busy lead',
          closingScript: 'Just texted the direct link to {{phone}}. Look forward to connecting later. Have a wonderful rest of your day!',
          disposition: 'callback_scheduled',
          sendSummarySms: true,
        },
      },
      {
        id: 'node-dnc-hangup',
        type: 'hangup',
        position: { x: 1450, y: 780 },
        data: {
          type: 'hangup',
          label: 'Polite DNC Disconnect',
          description: 'Honor opt-out request and tag CRM',
          closingScript: 'No problem at all. I have noted your preference and removed your number from our outreach. Thank you for your time.',
          disposition: 'dnc_requested',
          sendSummarySms: false,
        },
      },
    ],
    initialEdges: [
      {
        id: 'edge-greeting-vm',
        source: 'node-greeting',
        sourceHandle: 'voicemail',
        target: 'node-vm-hangup',
        data: { label: 'Voicemail / AMD', intent: 'voicemail' },
      },
      {
        id: 'edge-greeting-human',
        source: 'node-greeting',
        sourceHandle: 'human',
        target: 'node-value-pitch',
        data: { label: 'Human Answered', intent: 'human_connected' },
      },
      {
        id: 'edge-pitch-branch',
        source: 'node-value-pitch',
        target: 'node-intent-branch',
        data: { label: 'Caller Responds' },
      },
      {
        id: 'edge-branch-pos',
        source: 'node-intent-branch',
        sourceHandle: 'handle-pos',
        target: 'node-action-book',
        data: { label: 'Interested / Needs Savings', intent: 'positive' },
      },
      {
        id: 'edge-branch-price',
        source: 'node-intent-branch',
        sourceHandle: 'handle-price',
        target: 'node-rebuttal-price',
        data: { label: 'Budget Objection', intent: 'objection', isObjection: true },
      },
      {
        id: 'edge-rebuttal-book',
        source: 'node-rebuttal-price',
        sourceHandle: 'rebuttal-accepted',
        target: 'node-action-book',
        data: { label: 'Rebuttal Accepted' },
      },
      {
        id: 'edge-branch-busy',
        source: 'node-intent-branch',
        sourceHandle: 'handle-busy',
        target: 'node-action-callback',
        data: { label: 'Busy / Call Later', intent: 'busy' },
      },
      {
        id: 'edge-branch-dnc',
        source: 'node-intent-branch',
        sourceHandle: 'handle-dnc',
        target: 'node-dnc-hangup',
        data: { label: 'Not Interested / Remove', intent: 'dnc' },
      },
      {
        id: 'edge-book-hangup',
        source: 'node-action-book',
        target: 'node-success-hangup',
        data: { label: 'Booking Success' },
      },
      {
        id: 'edge-callback-hangup',
        source: 'node-action-callback',
        target: 'node-callback-hangup',
        data: { label: 'SMS Dispatched' },
      },
    ],
  },
  {
    id: 'healthcare-post-discharge',
    name: 'Healthcare Post-Op Follow-up',
    tagline: 'Empathetic clinical follow-up checking pain levels, medication & triage escalation',
    category: 'Healthcare & Patient',
    knowledge: {
      campaignId: 'healthcare-post-discharge',
      campaignName: 'Metro General Post-Surgical Recovery Call',
      description: 'Patient check-in 48 hours post-discharge to verify recovery, medication compliance, and escalate acute pain.',
      agentPersona: {
        name: 'Nurse Clara',
        role: 'Virtual Care Coordinator',
        company: 'Metro General Hospital',
        tone: 'empathetic',
        speakingRate: 0.92,
        voice: 'en-US-Standard-E',
      },
      leadProfile: {
        name: 'Robert Davis',
        company: 'Patient ID #MG-98102',
        phone: '+1 (555) 843-1920',
        email: 'robert.davis@example.com',
        attributes: {
          procedure: 'Laparoscopic Appendectomy',
          dischargeDate: 'Yesterday',
          attendingPhysician: 'Dr. Emily Vance',
        },
      },
      complianceNotice: 'This call is an automated health outreach from Metro General Hospital. If you are experiencing a life-threatening emergency, please hang up and call 911 immediately.',
      globalObjections: [
        {
          id: 'obj-emergency',
          trigger: 'I have severe chest pain / cannot breathe',
          response: 'Mr. Davis, please hang up immediately and call 911 or proceed to the nearest emergency room.',
          resumeFlow: false,
        },
      ],
      faqs: [
        {
          id: 'faq-pharmacy',
          question: 'Where was my prescription sent?',
          answer: 'Your discharge prescriptions were electronically sent to Walgreens on Maple Street. You can pick them up or request delivery.',
          keywords: ['prescription', 'pharmacy', 'medicine', 'medication', 'walgreens'],
        },
      ],
    },
    initialNodes: [
      {
        id: 'node-hc-greeting',
        type: 'greeting',
        position: { x: 400, y: 50 },
        data: {
          type: 'greeting',
          label: 'Patient ID & Wellness Greeting',
          description: 'Confirm identity of post-op patient',
          openingScript: 'Hello, this is Clara calling from Metro General Hospital for {{lead_name}}. Am I speaking with {{lead_name}}?',
          voiceStyle: 'Warm & empathetic',
          enableAmd: true,
          voicemailScript: 'Hello {{lead_name}}, this is Metro General Hospital checking on your recovery. Please call our nurse line at 555-0199 when you get a chance.',
        },
      },
      {
        id: 'node-hc-pain-check',
        type: 'question',
        position: { x: 400, y: 280 },
        data: {
          type: 'question',
          label: 'Pain Level Assessment (1-10)',
          description: 'Assess current discomfort and surgical incision pain',
          speechPrompt: 'I am glad to reach you, Robert. Dr. Vance wanted us to check in on how you are feeling today. On a scale from 1 to 10, how would you rate your pain right now?',
          variableToExtract: 'pain_score',
          allowBargeIn: true,
          maxWaitSeconds: 8,
          silencePrompt: 'Take your time, just let me know roughly from 1 to 10.',
        },
      },
      {
        id: 'node-hc-branch',
        type: 'scenarioBranch',
        position: { x: 400, y: 540 },
        data: {
          type: 'scenarioBranch',
          label: 'Triage Severity Evaluation',
          description: 'Route based on reported pain score and symptom severity',
          evaluationCriteria: 'Check if pain score is mild (1-4), moderate (5-7), or severe (8-10)',
          branches: [
            {
              id: 'branch-mild',
              label: 'Mild / Expected (1-4)',
              description: 'Normal recovery progression',
              intentKey: 'mild_pain',
              color: '#10b981',
              targetHandle: 'handle-mild',
            },
            {
              id: 'branch-severe',
              label: 'Severe / Acute (7+ or Fever)',
              description: 'Requires urgent clinical escalation',
              intentKey: 'severe_pain',
              color: '#ef4444',
              targetHandle: 'handle-severe',
            },
          ],
        },
      },
      {
        id: 'node-hc-escalate',
        type: 'action',
        position: { x: 650, y: 780 },
        data: {
          type: 'action',
          label: 'Live Nurse Transfer',
          description: 'Warm transfer directly to on-call triage nurse',
          actionType: 'live_transfer',
          actionConfig: {
            title: 'Post-Op Acute Pain Escalation',
            targetPhone: '+1 (555) 911-0199',
            crmTag: 'urgent_nurse_triage_escalation',
          },
        },
      },
      {
        id: 'node-hc-med-check',
        type: 'question',
        position: { x: 150, y: 780 },
        data: {
          type: 'question',
          label: 'Medication Adherence Check',
          description: 'Verify patient is taking prescribed antibiotic/pain meds',
          speechPrompt: 'That is encouraging to hear! Are you able to take your prescribed medications without any nausea or dizziness?',
          variableToExtract: 'medication_adherence',
          allowBargeIn: true,
          maxWaitSeconds: 6,
        },
      },
      {
        id: 'node-hc-success-end',
        type: 'hangup',
        position: { x: 150, y: 1040 },
        data: {
          type: 'hangup',
          label: 'Standard Follow-up Complete',
          description: 'Log positive recovery in EHR',
          closingScript: 'Wonderful. Keep resting, stay hydrated, and your follow-up with Dr. Vance is set for next Tuesday. Take care!',
          disposition: 'callback_scheduled',
          sendSummarySms: true,
        },
      },
      {
        id: 'node-hc-transfer-end',
        type: 'hangup',
        position: { x: 650, y: 1040 },
        data: {
          type: 'hangup',
          label: 'Transfer Connected',
          description: 'Connected to clinical staff',
          closingScript: 'I am connecting you right now to Nurse Jenkins. Please hold the line.',
          disposition: 'information_sent',
          sendSummarySms: false,
        },
      },
    ],
    initialEdges: [
      {
        id: 'edge-hc-1',
        source: 'node-hc-greeting',
        sourceHandle: 'human',
        target: 'node-hc-pain-check',
        data: { label: 'Patient Verified' },
      },
      {
        id: 'edge-hc-2',
        source: 'node-hc-pain-check',
        target: 'node-hc-branch',
        data: { label: 'Score Provided' },
      },
      {
        id: 'edge-hc-3',
        source: 'node-hc-branch',
        sourceHandle: 'handle-mild',
        target: 'node-hc-med-check',
        data: { label: 'Pain <= 5 (Normal)' },
      },
      {
        id: 'edge-hc-4',
        source: 'node-hc-branch',
        sourceHandle: 'handle-severe',
        target: 'node-hc-escalate',
        data: { label: 'Pain > 6 or Complications', intent: 'escalate' },
      },
      {
        id: 'edge-hc-5',
        source: 'node-hc-med-check',
        target: 'node-hc-success-end',
        data: { label: 'Meds Tolerated' },
      },
      {
        id: 'edge-hc-6',
        source: 'node-hc-escalate',
        target: 'node-hc-transfer-end',
        data: { label: 'Transfer Initiated' },
      },
    ],
  },
  {
    id: 'solar-home-qualification',
    name: 'Residential Solar Qualification',
    tagline: 'Qualifies homeowner status, electric utility bill threshold, and books site audit',
    category: 'Home Services & Energy',
    knowledge: {
      campaignId: 'solar-home-qualification',
      campaignName: 'SunBright Energy Federal Rebate Initiative',
      description: 'Outbound campaign reaching homeowners with average electric bills over $150/mo to book zero-down solar audits.',
      agentPersona: {
        name: 'Jordan Miller',
        role: 'Clean Energy Specialist',
        company: 'SunBright Energy',
        tone: 'friendly_professional',
        speakingRate: 1.02,
        voice: 'en-US-Standard-B',
      },
      leadProfile: {
        name: 'Michael Chang',
        company: 'Homeowner',
        phone: '+1 (555) 624-8110',
        email: 'mchang88@example.com',
        attributes: {
          address: '742 Evergreen Terrace, Springfield',
          estimatedBill: '$210/mo',
        },
      },
      complianceNotice: 'Calls are recorded for quality purposes. To opt-out at any point, simply say stop.',
      globalObjections: [
        {
          id: 'obj-cost-solar',
          trigger: 'Is solar expensive or will I have a loan?',
          response: 'Great question Michael! Under the current state clean energy initiative, qualified homeowners get zero out-of-pocket installation. You simply swap your high utility bill for a lower fixed solar bill.',
          resumeFlow: true,
        },
      ],
      faqs: [
        {
          id: 'faq-tax-credit',
          question: 'What is the federal tax credit percentage?',
          answer: 'The federal Inflation Reduction Act provides a 30% tax credit on the full installation value through 2032.',
          keywords: ['tax', 'credit', 'rebate', 'government', 'incentive'],
        },
      ],
    },
    initialNodes: [
      {
        id: 'node-sol-greeting',
        type: 'greeting',
        position: { x: 400, y: 50 },
        data: {
          type: 'greeting',
          label: 'Outbound Solar Pitch & Intro',
          description: 'Opening statement for neighborhood solar program',
          openingScript: 'Hi {{lead_name}}, this is Jordan from SunBright Energy. I am reaching out regarding the local zero-down solar rebate program in your area — do you own the property at {{address}}?',
          voiceStyle: 'Upbeat & professional',
          enableAmd: true,
        },
      },
      {
        id: 'node-sol-branch-owner',
        type: 'scenarioBranch',
        position: { x: 400, y: 280 },
        data: {
          type: 'scenarioBranch',
          label: 'Homeowner Verification Router',
          description: 'Ensure prospect is property owner before qualifying',
          evaluationCriteria: 'Determine whether prospect owns home or is a renter',
          branches: [
            {
              id: 'branch-owner-yes',
              label: 'Homeowner Verified',
              description: 'Yes, owns the property',
              intentKey: 'homeowner_yes',
              color: '#10b981',
              targetHandle: 'handle-owner-yes',
            },
            {
              id: 'branch-owner-no',
              label: 'Renter / Not Owner',
              description: 'Rents or not decision maker',
              intentKey: 'renter_no',
              color: '#ef4444',
              targetHandle: 'handle-owner-no',
            },
          ],
        },
      },
      {
        id: 'node-sol-bill-check',
        type: 'question',
        position: { x: 200, y: 540 },
        data: {
          type: 'question',
          label: 'Monthly Utility Bill Qualification',
          description: 'Ensure monthly electricity bill exceeds $120/mo threshold',
          speechPrompt: 'Awesome! On average, is your monthly electric bill typically over or under $130 per month?',
          variableToExtract: 'monthly_bill_range',
          allowBargeIn: true,
          maxWaitSeconds: 6,
        },
      },
      {
        id: 'node-sol-action-book',
        type: 'action',
        position: { x: 200, y: 800 },
        data: {
          type: 'action',
          label: 'Book Solar Roof Assessment',
          description: 'Dispatch solar design specialist for satellite roof analysis',
          actionType: 'calendar_booking',
          actionConfig: {
            title: 'Zero-Down Solar Assessment for {{lead_name}}',
            details: 'Address: {{address}}',
            crmTag: 'solar_qualified_inspection_booked',
          },
        },
      },
      {
        id: 'node-sol-renter-hangup',
        type: 'hangup',
        position: { x: 650, y: 540 },
        data: {
          type: 'hangup',
          label: 'Renter Disqualification',
          description: 'Politely exit as program requires property ownership',
          closingScript: 'Understood, Michael. Currently the state rebate requires property ownership. Thank you for your time and have a wonderful day!',
          disposition: 'disqualified_not_interested',
          sendSummarySms: false,
        },
      },
      {
        id: 'node-sol-success-hangup',
        type: 'hangup',
        position: { x: 200, y: 1040 },
        data: {
          type: 'hangup',
          label: 'Audit Scheduled & Close',
          description: 'Confirm appointment and text confirmation',
          closingScript: 'You are all set Michael! Our solar engineer will have your satellite roof mock-up ready for tomorrow at 2 PM. I just sent a confirmation text to {{phone}}.',
          disposition: 'meeting_booked',
          sendSummarySms: true,
        },
      },
    ],
    initialEdges: [
      {
        id: 'edge-sol-1',
        source: 'node-sol-greeting',
        sourceHandle: 'human',
        target: 'node-sol-branch-owner',
        data: { label: 'Connected' },
      },
      {
        id: 'edge-sol-2',
        source: 'node-sol-branch-owner',
        sourceHandle: 'handle-owner-yes',
        target: 'node-sol-bill-check',
        data: { label: 'Owns Home' },
      },
      {
        id: 'edge-sol-3',
        source: 'node-sol-branch-owner',
        sourceHandle: 'handle-owner-no',
        target: 'node-sol-renter-hangup',
        data: { label: 'Renter' },
      },
      {
        id: 'edge-sol-4',
        source: 'node-sol-bill-check',
        target: 'node-sol-action-book',
        data: { label: 'Bill > $130 (Qualified)' },
      },
      {
        id: 'edge-sol-5',
        source: 'node-sol-action-book',
        target: 'node-sol-success-hangup',
        data: { label: 'Audit Confirmed' },
      },
    ],
  },
];
